### ISSUE TITLE
question: I installed a new installation with Revancify, but I can't find the menu to export logs

### ISSUE THREAD

**Issue by sssh7710** [inotia00/ReVanced_Extended#1085]
### Application

YouTube

### Description

The menu is different from the old version, so I can't find the log export menu Let me know.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please add an explanation of what it means

Do you mean the debug logging included in RVX?
Or do you mean the logcat in Revancify?

**Comment by S23u512** [comment]
If you mean patch log txt file Revancify automatically creates it, there is no option to manually create it.

After patching Revancify will create your patch log file and put it in your documents folder.

![Screenshot_20230707_130633_My Files](https://github.com/inotia00/ReVanced_Extended/assets/138691006/7d52354c-4cbe-4052-ba4d-211ce932a831)

But, you need to restart your phone after patching in order to see this file.

**Comment by inotia00** [comment]
I am not a maintainer of Revancify
Ask on [Revancify's issue page](https://github.com/decipher3114/Revancify/issues) or in [Revancify's group chat](https://t.me/revancifychat).
