### ISSUE TITLE
bug: buttons don't stay hidden

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1103]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.25.39
ReVanced Patches v2.181.6

### Bug description

On YouTube v18.17.43 with patches v2.173.10 this bug never happened, something has changed.

https://github.com/inotia00/ReVanced_Extended/assets/127908708/6edaffa0-f4e0-480a-be83-16b7dcd6906f

(Watch the video till the end)

### Steps to reproduce

Shown in the video.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by User-noob2036876** [comment]
I came here to open this exact issue. Hide-button-container patch is buggy after inotia00's return.

**Comment by User-noob2036876** [comment]
Video in this issue is broken. But buttons seem like this
![Screenshot_20230708-221427_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/117031829/b58a7163-ab58-472e-980d-4d074d5c8e7f)

**Comment by User-noob2036876** [comment]
Like this![Screenshot_20230708-223752_ReVanced Extended.jpg](https://github.com/inotia00/ReVanced_Extended/assets/117031829/456ce261-76c6-43ce-994a-0d732023913f)

**Comment by S23u512** [comment]
Weird, I havent had a single issue with it.

**Comment by inotia00** [comment]
You are using Experimental Flags

**Comment by Kuddus73** [comment]
> You are using Experimental Flags

I get that but all I'm saying is that the bug never happened on the last version released before your return.

**Comment by inotia00** [comment]
Even in previous releases, action buttons were designated as `Experimental Flags`
Even in previous releases, that patch didn't work for some people.

This bug occurs because action buttons have been changed to a structure that is more difficult to filter in the latest YouTube version.

Anyway It's hard to filter out action buttons designated as `Experimental Flags` any longer without bugs, so I will remove the settings hiding action buttons designated as `Experimental Flags` in the next release (just like the official ReVanced)

**Comment by inotia00** [comment]
I got too many bug reports before flagging this as an `Experimental Flags`, and promised to remove this patch if it no longer works

https://github.com/inotia00/ReVanced_Extended/issues/383 https://github.com/inotia00/ReVanced_Extended/issues/541 https://github.com/inotia00/ReVanced_Extended/issues/712

**Comment by S23u512** [comment]
Please do not remove this patch, its working flawlessly on my end and I believe this is working with others peoples phones too. Only because there are a handful of people saying this is not working doesnt mean that you need to remove this patch entirely.

If this patch gets removed then I must say goodbye, I refuse to update to the latest version.

If someone reports that this is not working just ignore them.

**Comment by inotia00** [comment]
You may find it hard to believe, but I've already done dozens of code refactorings and rewrites to fix this issue in the last 5 months.
but no success and users are constantly reporting about this bug.

At least I've tried my best to fix this issue, but I've found that a fix is no longer possible on my side.

So I just removed the patch
If anyone can fix this patch, please open a PR

I'm already tired of refactoring and rewriting code dozens of times, so I won't be maintaining it anymore.

**Comment by inotia00** [comment]
I can't fix this bug, but I can make the `Experimental Flags` visible on versions that don't reproduce the bug

This bug is not reproducible in YouTube v18.20.39, so including the `hide-button-container` patch in YouTube v18.20.39 will make the `Experimental Flags` re-exposed (revanced-patches-2.184.1+)

**Comment by devilboy1122** [comment]
![Screenshot_2023-07-22-20-08-22-130_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/79780868/df511e2f-8e15-4f0a-abc0-08cef9806230)
![Screenshot_2023-07-22-20-06-34-026_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/79780868/234dd529-3bff-42dd-9275-f8f05445bc31)
![Screenshot_2023-07-22-20-06-06-403_app rvx android youtube-edit](https://github.com/inotia00/ReVanced_Extended/assets/79780868/88b7e0c7-f9b3-485a-ae84-e82d938334e0)
Remix Button didn't hidden please fix
