### ISSUE TITLE
BUG: youtube crashes after tapping the cast button on homescreen

### ISSUE THREAD

**Issue by tarek133** [inotia00/ReVanced_Extended#117]
### Type

Error at runtime

### Application

YT Revanced Extended (Magisk) 18.0.1.35

### Bug description

When tapping on the cast button at the homescreen/feed while I'm connected to my TV, YouTube immediately crashes. Connecting my TV with the button works, it's just crashing when the TV is already connected and you tap on it.

### Steps to reproduce

See above.

### Relevant log output

```shell
none yet
```

### Device Environment

Android 12, Motorola Edge 30 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unfortunately, it's not an environment I can test on

Now I don't have a ROOT device, and I can't cast to the TV.
(Even Android Studio does not provide an environment to test cast)

Instead, it might help me to fix the issue if you attach the error log when the crash occurs

**Comment by tarek133** [comment]
I see. I just know for sure that this issue wasn't there in the previous .32 build. It just started happening when updating to .35 build.
I uploaded the log here: https://krakenfiles.com/view/FjSpl6bOTU/file.html

**Comment by inotia00** [comment]
I checked the logcat, but it was not an error related to code.

This error does not work sometimes because the Detach module does not work from time to time, so the YouTube is automatically updated by Google Play Store,

Or it is estimated to be an error that occurs when the resource file is broken in the compile process.

I have a chance to cast with TV today

Therefore, the test was conducted on two devices.

Test version
: RVX V18.01.35

![NON_ROOT](https://user-images.githubusercontent.com/108592928/211185193-c3648367-9f6f-4751-93f2-d0f7c9bb87b4.png)

1. Non-Root device
-When pressing the cast button on the player
: Working well
-When pressing the Cast button on the homes screen
: Working well
-Player control operation after casting
: Working well

![ROOT](https://user-images.githubusercontent.com/108592928/211185217-c604c6ca-412c-4b24-a487-b259d11b038f.png)

2. ROOT device
-When pressing the cast button on the player
: Working well
-When pressing the Cast button on the homes screen
-Player control operation after casting
: Working well

**Comment by tarek133** [comment]
Damn I see. So it is a me problem then I guess? Its just so weird because as soon as I revert back to the .32 build, everything works fine again.

**Comment by tarek133** [comment]
Ok its actually not only me, I just checked the telegram group and someone else is having this exact issue. I will ask him for logs
![Screenshot_20230108-091120~2](https://user-images.githubusercontent.com/12681440/211186621-5d5148bf-2400-4b1b-8b5b-86a6b318400a.png)

**Comment by tarek133** [comment]
Heres the other log from the other guy with the same issue:
https://pastebin.com/e08EZ3Tm

**Comment by inotia00** [comment]
I checked the log

This is an issue with builds provided in the RVX Lite channel

**Comment by tarek133** [comment]
What can be done to fix it?

**Comment by inotia00** [comment]
Proceed with the build according to the documentation
https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android)
