### ISSUE TITLE
I don't know if it's bug or not 

### ISSUE THREAD

**Issue by KimYo2** [inotia00/ReVanced_Extended#1182]
### Application

Other

### Description

I don't know the problem in YouTube/micro g

![Screenshot_2023-07-17-21-06-28-486_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125992636/b0967a1f-137c-4b12-aa7e-f6933191a8a6)
![Screenshot_2023-07-17-21-06-33-433_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125992636/08cec736-23ba-4012-a5bf-b9cf590b7988)
No 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is a phenomenon that occurs when MicroG fails to retrieve Google account information for some reason.

This happens when the system OS is killing MicroG, or when you change the password for your Google account.

Remove your Google account from system settings and log in again.
issue will be resolved
