### ISSUE TITLE
bug: enabling `Disable playlist autoplay` also enables `Always repeat`

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1208]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.27.35
ReVanced Patches v2.186.1

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/69afb955-b1cb-45ad-92da-670e49418418

### Steps to reproduce

Shown in the video.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
What is the issue

**Comment by Kuddus73** [comment]
When you hold the button, it simultaneously enables `Disable playlist autoplay` and `Always repeat`.

It shouldn't turn on `Always repeat` if you **hold** the button.

**Comment by inotia00** [comment]
![20230724_192609](https://github.com/inotia00/ReVanced_Extended/assets/108592928/d3dec199-9ca2-479a-b912-ad6427683807)

To be exact, it's more like `pause after repeat` than `disable autoplay` (as shown in the setting)

Because the video is paused after the auto-repeat, it also acts as a disable autoplay

So we can't separate the two
(`pause after repeat` depends on `always repeat`)

When the repeat button is off, tap and hold, then `pause after repeat` turns on, and `always repeat` also turns on

This is the intended action
