### ISSUE TITLE
Default Quality control

### ISSUE THREAD

**Issue by Mhmodhaha** [inotia00/ReVanced_Extended#1310]
### Type

Other

### Tools used

ReVanced Manager

### Application

Youtube v18.27.40 and v18.24

### Bug description

When choosing a specific quality from revanced extended setting (under video secrion)
 it works but not always 
Ex.when choosing default quality on WiFi it works when opening first video but when open another one it turns into auto quality so I have go exit video and open it again or even more to solve this problem
In old version 18.17 it worked properly so I'm using it now.
So I hope you figure out why it keeps changing to auto quality not a default one

### Steps to reproduce

I didn't  understand 

### Relevant log output

```shell
Nothing
```

### Screenshots or videos

![Screenshot_20230802_063508_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/141293135/0e6a89fe-0054-4c16-9381-b230864103bf)
This when using default video quality on WiFi it is still on auto mode......

### Solution

I close the video and open it again and keep doing this until it turns to this screenshot 

![Screenshot_20230803_054628_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/141293135/35e67f39-a82f-41ef-9dad-b4715226664f)

### Additional context

Note: it works very well on v18.17 
But in v18.24 and 18.27 it is buggy 
I hope you can solve it because really  i depend on this feature to save data .

### Device Environment

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/321

**Comment by Mhmodhaha** [comment]
Does it solved in v18.29 or something else happened?

**Comment by inotia00** [comment]
1. This is an issue that received too many reports
: Since there are already duplicate issues, I have closed the issue.

2. It is not reproduced in my side (maybe a/b tests?)
: In other words, it is not an issue I can fix

3. Perhaps this is an Issue of latest YouTube (stock YouTube)
: The following two posts in r/youtube show that this issue is also reproduced in stock YouTube

https://www.reddit.com/r/youtube/comments/14yqlo5/why_did_the_quality_of_the_videos_im_watching_are/

https://www.reddit.com/r/youtube/comments/14z6uzx/why_does_youtube_videos_keep_randomly_switching/

Try to patch YouTube v18.20.39, the minimum supported version by RVX, and clean install

It may help to solve the issue

**Comment by Mhmodhaha** [comment]
> @inotia00 Iam very Sorry for bothering you Does it solved in v18.29 or something else happened?

@inotia00 
I didn't try as I can't patch RVX 
I wait for RVX lite telegram channel to patch new versions and install them
