### ISSUE TITLE
feat(patch): add `custom-playback-speed` patch for YouTube Music 

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1338]
### Application

YouTube Music

### Issue

Sorry, i think i dont need to describe the patch, u understand, if not ask me

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Unusually, YT Music is structured so that it does not allow custom speeds to be defined.

Therefore, this cannot be implemented with the current method, and there is no reason to implement it.

**Comment by inotia00** [comment]
When I checked the source code in YT Music, the limit for adjusting the playback speed on the client side was 2.0x speed.

In other words, it is impossible to apply the desired speed within the range of 0.0x to 10.0x like YouTube.

I thought this issue was invalid for this reason, so I closed it.

However, it is possible to apply the desired speed within the range of 0.0x to 2.0x.
(This is more of just a speed granularity option)

If you think you need this patch, please re-open an issue

**Comment by girshcatt** [comment]
Yes, anyway this will be useful function even is limit 2x, i dont know how to reopen issue best way, i will just open it as patch request with same name and i will tag your comment
