### ISSUE TITLE
question: Why patches are not alphabetized?

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#1369]
### Application

YouTube

### Description

Is there a reason why patches are not in proper alphabetical order? Capital letters are sorted before lowercase letters. Same for YTMusic.

<img src="https://github.com/inotia00/ReVanced_Extended/assets/125728453/b490db6e-c682-4cac-ac6a-f429d5b43a59" width="400" height="400">
<img src="https://github.com/inotia00/ReVanced_Extended/assets/125728453/37ef53a8-fb7d-47e9-9c6c-d801031c07b9" width="400" height="400">
<img src="https://github.com/inotia00/ReVanced_Extended/assets/125728453/15bba1c4-59f8-424b-adca-ae20d6f8178d" width="400" height="400">
<img src="https://github.com/inotia00/ReVanced_Extended/assets/125728453/88bc7ebf-1af4-40f8-afcb-7a09f76a3bda">

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The README.MD is provided for CLI users, listing all patch names converted based on CLI commands.
(In CLI, you have to use the `-e microg-support` command instead of `-e MicroG support`)

This is why all uppercase letters are converted to lowercase in the README.MD.

Revancify uses the actual patch names rather than pulling them from the README.MD, which is why uppercase and lowercase letters are listed without conversion.

Also, according to lexicographic sorting, it is more accurate for uppercase letters to come before lowercase letters.
