### ISSUE TITLE
bug(YouTube): correct `spoof-app-version` for 18.20.39 and 18.19.36

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1378]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.19.36 ~ 18.20.39

### Bug description

Can you change spoof app version function when you patch 18.20.39 or 18.19.36? Because in these versions 18.20.39 version in spoof app version useless and may cause issues

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
I will list some reasons

1. `spoof-app-version` patch is literally a patch that spoofs the client version submitted to the server

so it is not an `old-layout` patch

spoofing with a higher version than the current client is also possible

as a representative example, when spoofing from YouTube v18.19.36 to v18.24.35, the `Hook download button` switch is designed to be activated


2. `spoof-app-version` patch is an `Experimental Flag`

therefore it is not always stable and bugs occur quite often

this patch is provided for users who are aware of this and will use it


3. changing the target version includes changes to language resources as well as source code

this means that all translations need to be updated


For this reason I will not fix

**Comment by girshcatt** [comment]
Ok,  after your explain i have one question, do you mean that we can spoof version on newer than version we use and in fact update youtube without update?

**Comment by inotia00** [comment]
In theory it is possible

If there is code on the client side to handle the layout loaded from the server side, there is no major issue.

If the layout loaded from the server side changes significantly and the client side cannot handle it, the layout may be broken.
(As a representative example, if you try to spoof YouTube from v17.34.36 to v18.01.38, no layout will be loaded)

Since this is probably not the situation the developer intended, it is best to use it only for testing purposes.
