### ISSUE TITLE
bug: Excluding 'custom-package-name' patch overrides default package name

### ISSUE THREAD

**Issue by hlytus** [inotia00/ReVanced_Extended#1388]
### Type

Error while patching

### Tools used

Revancify

### Application

Youtube - 18.31.40, 18.35.35
YouTube music

### Bug description

Even if the `custom-package-name` patch is excluded it still patches with the package name that is entered in the options file. 

In the past, if the patch was excluded it used app.rvx.android.youtube as default, ignoring what was present in the options file.

### Steps to reproduce

1. Change package name in options file
2. Exclude `custom-package-name` and patch youtube.

Output app will have the package name that was in the options file.

### Relevant log output

```shell
_
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
Even if you exclude the `custom-package-name` patch, the `custom-package-name` patch is included if you include the `microg-support` patch.

From the beginning, the `custom-package-name` patch cannot be forcibly excluded or included.

Due to structural limitations of ReVanced-Patcher, OptionsContainer cannot be added to the `microg-support` patch.

So I separated it into `microg-support` patch and `custom-package-name` patch.
(In other words, you can just think of the `custom-package-name` patch as the same as the `microg-support` patch)

1. If you do not want to use the `custom-package-name` patch, you must also exclude the `microg-support` patch.
2. Even if you include the `custom-package-name` patch, the package name will not change unless you exclude the `microg-support` patch.

**Comment by KobeW50** [comment]
> 2. Even if you include the `custom-package-name` patch, the package name will not change unless you exclude the `microg-support` patch.

I'm having trouble understanding this, as I always include the `microg-support` patch (along with the `custom-package-name` patch) and the custom package name (specified in the patch options) is applied

**Comment by hlytus** [comment]
If `microg-support` is included, `custom-package-name` is also included with it even if you exclude it, so it will patch with whatever is entered in the options file.

But if you don't include `microg-support` patch then custom package name will not be applied and it will use the default YouTube package name i.e. com.google.android.yoututbe

In my understanding, `custom-package-name` is useless.

**Comment by inotia00** [comment]
> If `microg-support` is included, `custom-package-name` is also included with it even if you exclude it, so it will patch with whatever is entered in the options file.
> 
> But if you don't include `microg-support` patch then custom package name will not be applied and it will use the default YouTube package name i.e. com.google.android.yoututbe
> 
> In my understanding, `custom-package-name` is useless.

You understood correctly.. just think of `custom-package-name` as effectively a dummy patch.

Nevertheless, the reason it is shown in the patch list is because if I make it hidden in the patch list, the `custom-package-name` option is not added to `options.json`.

This is a structural limitation of the current ReVanced-Patcher.

**Comment by hlytus** [comment]
> Nevertheless, the reason it is shown in the patch list is because if I make it hidden in the patch list, the custom-package-name option is not added to options.json.

ohk. makes sense.

**Comment by inotia00** [comment]
While looking at the latest ReVanced Patches, I found out that this can be implemented in a fairly complicated way.

This will be reflected in the next release.
