### ISSUE TITLE
feat(YT Music/Replace dismiss queue): add an option to stop track playing in YTM when you redirected to YT

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1429]
### Application

YouTube Music

### Issue

Add option in `replace-dismiss-queue` to stop track playing in YTM automatically when you get redirected to YT

### Acknowledgements

- [X] I have searched the existing issues and this is not a duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Let's assume that the user clicks 'Open In YouTube' with 'Continue watching' turned on and does not open YouTube for 60 seconds in the app selection window.

If the audio is not paused, the link will open 60 seconds earlier.

If the audio is not paused and the user moves on to the next track while trying to decide which YouTube app to open, the information for the previous track will remain in the app selection window.

There is still a possibility that minor bugs like this may occur, and they cannot be fixed due to limitations in the way the app is implemented - unless the current audio is paused.

That's why I forced the audio to pause.
