### ISSUE TITLE
bug(SponsorBlock): 3 settings can't be imported/exported

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1435]
### Type

Other

### Tools used

Revancify

### Application

YouTube v18.32.39

### Bug description

The bug is explained well here:
https://github.com/YT-Advanced/YT-Advanced/issues/47.

### Steps to reproduce

https://github.com/YT-Advanced/YT-Advanced/issues/47

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
The import/export settings feature for the ReVanced Extended settings are [only meant for the ReVanced Extended settings](https://github.com/inotia00/ReVanced_Extended/issues/1428#issuecomment-1736488088)

And those settings cant be added to the SponsorBlock json because [the json must be compatible with the import feature for the SponsorBlock browser extension](https://github.com/inotia00/ReVanced_Extended/issues/179#issuecomment-1439275792)

**Comment by KobeW50** [comment]
The import/export settings feature for the ReVanced Extended settings are [only meant for the ReVanced Extended settings](https://github.com/inotia00/ReVanced_Extended/issues/1428#issuecomment-1736488088)

And those settings cant be added to the SponsorBlock json because [the json must be compatible with the import feature for the SponsorBlock browser extension](https://github.com/inotia00/ReVanced_Extended/issues/179#issuecomment-1439275792)

**Comment by Kuddus73** [comment]
> The import/export settings feature for the ReVanced Extended settings are [only meant for the ReVanced Extended settings](https://github.com/inotia00/ReVanced_Extended/issues/1428#issuecomment-1736488088)
> 
> And those settings cant be added to the SponsorBlock json because [the json must be compatible with the import feature for the SponsorBlock browser extension](https://github.com/inotia00/ReVanced_Extended/issues/179#issuecomment-1439275792)

But this bug was fixed on **ReX** [v2.188.2](https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.188.2) tho.

**Comment by KobeW50** [comment]
This can't be fixed without either making the SponsorBlock json incompatible with other SponsorBlock platforms unless the settings are included in the export/import of ReVanced Extended settings, which inotia00 recently said he doesn't plan on adding. Maybe if a pr is made he would do it

**Comment by inotia00** [comment]
bug is something that doesn't work as the dev intended.

as mentioned above, this is a value that the dev intentionally registered as an exception so that it cannot be imported or exported to ensure compatibility with Chrome Extensions

import/export settings works as the dev intended, so it can't be called a bug
