### ISSUE TITLE
question: will you be shifting to revanced manager compose

### ISSUE THREAD

**Issue by ansarimohammed422** [inotia00/ReVanced_Extended#1461]
### Application

Other

### Description

As wee know revanced manager compose is going to release soon

So will we be seeing RVX Manager compose also

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
RVX Manager compose is not yet officially released

Also, the reason I provide the RVX Manager build is for users who are not familiar with TUIs like rvx-builder or Revancify, not because I prefer to use the RVX Manager

So even if RVX Manager compose is officially rolled out in the future, I have no plans to move to it
