### ISSUE TITLE
bug(YouTube Music/Replace cast button): open music button redirect you to first track in playlist

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1486]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

YouTube Music 6.15.52 ~ 6.21.51

### Bug description

Open music button redirect you to first track in playlist

https://github.com/inotia00/ReVanced_Extended/assets/110785596/2b1bc0c0-3719-4a51-b0b8-c43120d40740

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
The `Replace cast button` patch is a patch added for testing purposes.
So I excluded this patch by default

If there is even one unplayable song in the playlist, this error seems to occur

Additionally, the `Video Type Hook` patch is required for the `Replace cast button` patch, but this patch is too easily broken depending on the version of YouTube Music

In other words, the `Replace cast button` patch does not seem to be an appropriate patch to support a wide range of versions

Since `Replace cast button` patch is unsuitable patch for long-term maintenance, I will remove this patch from the next release

**Comment by girshcatt** [comment]
Please can you just leave it as patch with side effects and not for all versions? I can live with all these things, this function so cool and useful, that will be such a pity if you will remove it 😥 This is option that i use literally every day. Just mark this patch as it has some issues and that you wont solve any problems with it if you want

**Comment by inotia00** [comment]
Anyway, I'm not accepting bug reports for experimental flags, so I'm closing the issue
