### ISSUE TITLE
suggestion(YouTube Music/Custom playback speed): do the same speed values as in YouTube by defalut if patch applied

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1488]
### Application

YouTube Music

### Description

Do the same speed values as in YouTube by defalut if patch applied. I mean if you turn on custom playback speed in YouTube by defalut you get these speed values: 0.25\n0.5\n0.75\n1.0\n1.25\n1.5\n1.75\n2.0\n2.25\n2.5
In YTM with `custom-playback-speed` patch applied you have only 0.25\n0.5\n0.75\n1.0\n1.25\n1.5\n1.75\n2.0 by defalut, change values by defalut to the same as in YT

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
YouTube and YouTube Music have a slightly different way of applying the playback speed patch

Because of the limits of the app structure of YouTube Music, the enable/disable custom playback speed toggle cannot be added

Therefore, the custom playback speed array will overwrite the default playback speed array

This is why in YouTube Music, the default value of the custom playback speed array matches the default value of the default playback speed array

If I don't do this, I won't be able to make the custom playback speed patch and the enable playback speed patch (flyout panel) as independent patches

For this reason, this suggestions cannot be applied
