### ISSUE TITLE
Just want to ask 

### ISSUE THREAD

**Issue by KimYo2** [inotia00/ReVanced_Extended#1491]
### Application

Other

### Description

Is there no patch for mMicroG?. Oh and one more, my friend(first time user) just ask me is there any revanced/revanced extended for desktop pc/ Windows pc?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KimYo2** [comment]
I just want to hide the apk icon

**Comment by girshcatt** [comment]
No, patches for mMicroG was some time ago, but they was removed because they did much confuse to users. If you want to hide app icon i just recommend you to switch to https://github.com/inotia00/VancedMicroG/releases/latest, it has just no issues, i hope that you understand that if it based on a little bit old gsm services this not mean that it not good. This is the best working and safe microg ever.

About ReVanced Extended for PC. Of couse no, because RVX is patches for YT on android, there is nothing for PC, you can just use chrome extensions: SponsorBlock, Return YouTube Dislike, De Arrow, uBlock origin but nothing else

PAY ATTENTION PLEASE!!! If i answered all you questions please close issue 🙏
