### ISSUE TITLE
bug(Youtube): Black screen when return to the foreground during background

### ISSUE THREAD

**Issue by S1iuuuuuuuuuuuuuuu** [inotia00/ReVanced_Extended#1513]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Youtube 18.31.40 v2.190.1 ~ 18.33.40 v2.193.4 (Non-root)

### Bug description

A black screen is displayed when return to the foreground during background play.

Similar issue: https://github.com/ReVanced/revanced-patches/issues/2991

### Steps to reproduce

1. Play any video.
2. Switch to PIP mode.
3. Press the background play button.
4. Return to the foreground.

### Relevant log output

```shell
None
```

### Solution

I found two solutions:

A. Disable the pip mode option in settings
Or
B. Turn off the phone screen and turn it back on.

### Device Environment

Android 10 arm64-v8a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by KobeW50** [comment]
Is it the same black screen as in this issue?
https://github.com/inotia00/ReVanced_Extended/issues/1510

**Comment by inotia00** [comment]
yeah it's a duplicate issue

**Comment by S1iuuuuuuuuuuuuuuu** [comment]
@KobeW50 I tried to reproduce that issue using 18.31.40 v2.190.1 and 18.33.40 v2.193.4, but it didn't occurred.

**Comment by Hennadz** [comment]
> Is it the same black screen as in this issue? #1510

No. This is another question.
There https://github.com/inotia00/ReVanced_Extended/issues/1510 dude just needs to enter his YouTube account and external links will open in the entire player.

I also have the problem of a black screen when returning from the background. I In search of its cause, I applied only three necessary patches (non-root) - the problem persists. Should I open a new thread, or should we continue here?

**Comment by inotia00** [comment]
> I also have the problem of a black screen when returning from the background

Issues related to it also already exist https://github.com/inotia00/ReVanced_Extended/issues/1482

**Comment by Hennadz** [comment]
@inotia00 
I recorded the screen with sound so that you can understand that this is not buffering (as we understand it). 99 MB (1:19 min). I know this is a difficult question, but the latest patch update covers the entire range of recommended versions with this bug. All that remains is to use patch 2.190.18. This nonsense has not yet appeared there.
Let me know if this information is needed to solve this problem.

![VideoCapture_20231011-002317](https://github.com/inotia00/ReVanced_Extended/assets/130844239/2c0f689b-b8ba-490a-a635-5ad207d18c7e)
![VideoCapture_20231011-002110](https://github.com/inotia00/ReVanced_Extended/assets/130844239/1a40afe8-1637-4d19-8e79-ea0d88f12d6a)
![VideoCapture_20231011-002230](https://github.com/inotia00/ReVanced_Extended/assets/130844239/d80a391d-45bc-484c-82c6-e602dfd315e8)
![VideoCapture_20231011-002219](https://github.com/inotia00/ReVanced_Extended/assets/130844239/d9a1645f-63f0-4e2d-a997-4ea2908af9ff)

**Comment by inotia00** [comment]
Since it doesn't reproduce at all on my side, I can't fix it even if you let me know

**Comment by Hennadz** [comment]
@inotia00 
There are several observations on this issue. The glitch appears after the new layout is fully loaded. With a clean installation, version 18.24.37 is not buggy, but version 18.36.39 is buggy. There will be no bug if 18.36.39 is installed as an update to the working version.. Patches v2.193.8 did not bring anything new on this issue. Just checked. Apparently something on the server side.
