### ISSUE TITLE
bug(YouTube/Hide navigation buttons): Disabe `Switch create button with notifications button` doesn't work

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1563]
### Type

Error while patching

### Tools used

ReVanced Manager

### Application

YouTube v18.39.41
Patches v2.193.18

### Bug description

This bug doesn't occur when the phone's language is English.
When the phone is in Italian language (maybe also other languages too) after enabling `Switch create button with notifications button`, the disabling of this option desn't work (or at least it doesn't work properly because by closing and opening many times or by force stopping the app it does disable it eventually).

https://github.com/inotia00/ReVanced_Extended/assets/127908708/52fd68c0-6f88-494a-b661-13f913aaad7d

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
Because when you force-close the app, it will break the Settings

**Comment by inotia00** [comment]
Issue does not reproduce in Italian environment

**Comment by girshcatt** [comment]
I facing this issue too, only solution is to trigger layout to update, i cant clearly explain it

**Comment by inotia00** [comment]
Now I can reproduce this issue

This issue is quite interesting
Settings will not take effect until you reboot the device

In the debug log, the settings were applied correctly
That said, the patch works fine

For some reason the client is not applying this value immediately
Therefore, RVX patches cannot fix this issue

In the next release, I will add the following description to settings:
`If this settings does not work, reboot your device`

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.195.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.195.1)
