### ISSUE TITLE
Custom branding icon option doesn't exist

### ISSUE THREAD

**Issue by Turhvjbufv** [inotia00/ReVanced_Extended#1601]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube, every version 

### Bug description

There is no patch to change the yt icon, there is only custom branding YouTube name patch 

### Steps to reproduce

Go to RVX manager, patch YouTube, no custom branding icon patch

### Relevant log output

```shell
Non
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
RVX Patches only provides three preset icons:
- `Custom branding icon MMT`
- `Custom branding icon Revancify Blue`
- `Custom branding icon Revancify Red`

`Custom branding icon` patch does not exist

**Comment by Turhvjbufv** [comment]
I know, I'm asking why a universal one(like in revanced, so we can do any icon we want) doesn't exist.
Please close as not planned

**Comment by inotia00** [comment]
This is because RVX Patches already provides three types of icon sets

If you are using the ReVanced CLI, you can set a custom icon even without the `Custom branding icon` patch

Although it is not mentioned in any documentation, I will briefly describe the steps here:
1. Create a folder named `branding` in the path where ReVanced CLI exists
2. Proceed with patching with ReVanced CLI
3. The icons will be copied inside a folder named `branding`
4. Replace these icons with the icons you want
5. Exclude all of the following patches and proceed with the patch again
- `Custom branding icon MMT`
- `Custom branding icon Revancify Blue`
- `Custom branding icon Revancify Red`
6. The patch is complete with the icon you want

For YouTube Music, you can apply custom icon by creating a folder named `branding-music` instead of a folder named `branding`
