### ISSUE TITLE
question(YouTube): how can I get new layout on 18.29.38?

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1619]
### Application

YouTube

### Description

How can I get new layout on 18.29.38? Is it possible? And do you know all versions affected by new layout?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I couldn't get the new layout in the old version in any way
I think this is because new layout depends on the server side

The minimum version for which new layout is applied is `YouTube v18.36.39`, and in versions lower than this, new layout does not applied even if you use the `Spoof app version` patch
