### ISSUE TITLE
suggestion: Clarify Description of Video Codec Type

### ISSUE THREAD

**Issue by Stale-1** [inotia00/ReVanced_Extended#1633]
### Application

YouTube

### Description

1) The Video Codec Type is kinda confusing, if its turned on do I get VP9 or HDR? 

Maybe change the description to;
a) Enable = VP9 | Disable = HDR
b) Enable = HDR | Disable = VP9

or change the description to;
c) HDR enabled
d) VP9 enabled
![Screenshot_20231101_070729](https://github.com/inotia00/ReVanced_Extended/assets/74855954/4239f2e0-5bc4-44a6-a19c-0cd0a7390ee3)
![Screenshot_20231101_070719](https://github.com/inotia00/ReVanced_Extended/assets/74855954/7bec67ec-0f7b-4591-8bda-246fa9e29b99) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The HDR codec enabled by the `Force video codec` patch is the hardware HDR codec

`Disable HDR video` patch disables both software HDR codec and hardware HDR codecs
(HDR codecs handled by `Disable HDR video` patch and `Force video codec` patch are different)

Software HDR codecs and hardware HDR codecs are different from a technical point of view, but I can't write it as the same codec because I'm not professional in video codecs

Someone who knows video codecs better than me may think it's wrong to integrate them into one patch

So I can't integrate them into one

**Comment by Stale-1** [comment]
> The HDR codec enabled by the `Force video codec` patch is the hardware HDR codec
> 
> `Disable HDR video` patch disables both software HDR codec and hardware HDR codecs (HDR codecs handled by `Disable HDR video` patch and `Force video codec` patch are different)
> 
> Software HDR codecs and hardware HDR codecs are different from a technical point of view, but I can't write it as the same codec because I'm not professional in video codecs
> 
> Someone who knows video codecs better than me may think it's wrong to integrate them into one patch
> 
> So I can't integrate them into one

I now understand why it wasn't a thing before thanks for explaining. I guess clarifying the description of the patch settings is enough so it isn't confusing what Codec is currently enabled.
