### ISSUE TITLE
question: what is the different between these two patches?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#1638]
### Application

YouTube

### Description

![Screenshot_20231101_185736_RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/130296934/3f106887-8dbb-4873-98e4-3657c002112f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Force mean that you wont have option to switch between enabled and disabled player buttons background

**Comment by inotia00** [comment]
The two patches have different working methods

The `Hide player button background` patch is applied to the `smali` code
Therefore, after the patch is applied, on/off control is possible through the switch in the settings.

This `Hide player button background` patch has the following issues: https://github.com/inotia00/ReVanced_Extended/issues/569

For this reason `Force hide player button background` was added

The `Force hide player button background` patch is applied to the `xml` instead of being patched to the smali code.
Therefore, after the patch is applied, on/off control is not possible through the switch in settings.
