### ISSUE TITLE
Tap left right to seek

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#1640]
### Application

YouTube

### Description

" Tap left right to seek" Is it possible to add it in the new version?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] This is not a feature request for YouTube.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Tapping to seek is already a native YouTube feature and isn't removed in YT ReVanced Extended

**Comment by Mehedi5585** [comment]
> Tapping to seek is already a native YouTube feature and isn't removed in YT ReVanced Extended
> 
> Edit: if you mean "swipe left or right to seek" then that generally only is available while the video is paused (even in the official YouTube app)

You are absolutely right.  But I mean is it possible to use it without paused the video

**Comment by KobeW50** [comment]
> is it possible to use it without paused the video

I believe that using a slightly older version will allow you to do that. I currently have the latest patches on v18.25.40 and can slide-to-seek. You can see all supported versions in the JSON within the README in the [patches repository](https://github.com/inotia00/revanced-patches#-json-format).

I tried spoofing the app version from 18.40.34 to 18.25.40 but that didn't allow me to use the feature, so you may need the actual version to be an older one instead of just spoofing to an older one.

I'm not sure if the slide-to-seek has the a/b tests label for older versions, which would mean the availability would vary based on account and device.

**Comment by Mehedi5585** [comment]
> > is it possible to use it without paused the video
> 
> I believe that using a slightly older version will allow you to do that. I currently have the latest patches on v18.25.40 and can slide-to-seek. You can see all supported versions in the JSON within the README in the [patches repository](https://github.com/inotia00/revanced-patches#-json-format).
> 
> I tried spoofing the app version from 18.40.34 to 18.25.40 but that didn't allow me to use the feature, so you may need the actual version to be an older one instead of just spoofing to an older one.
> 
> I'm not sure if the slide-to-seek has the a/b tests label for older versions, which would mean the availability would vary based on account and device.

Thanks Dear,
