### ISSUE TITLE
question: <Youtube/Thumbnails>: Any way to force disable new thumbnail preview?

### ISSUE THREAD

**Issue by NikunjKhangwal** [inotia00/ReVanced_Extended#1665]
### Application

YouTube

### Description

I disabled the "enable new thumbnail preview" while patching. But I'm still seeing the new preview. I saw someone mentioning this a feature test by Google but is there a way to forcefully disable it right now and get old preview back?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Normally you can force disable it by turning off `Enable new thumbnail preview`.
Since `new thumbnail preview` is server-side dependent, you may not be able to disable it if new A/B tests are applied.

The `Enable new thumbnail preview` patch is not aimed at disabling it, but rather to force enable `new thumbnail preview` on lower versions.

In other words, if you patch to a low enough version, `new thumbnail preview` will not be enabled.

The versions currently supported by the patch are YouTube v18.25.40 ~ YouTube v18.40.34, so I recommend patching one by one, starting with the lowest version.

**Comment by NikunjKhangwal** [comment]
Ah! Understandable. I want to stay updated with both the patches and YT itself so i guess I'll deal with it for now. Thanks for the answer.
