### ISSUE TITLE
question(YouTube): what means browse id?

### ISSUE THREAD

**Issue by girshcatt** [inotia00/ReVanced_Extended#1752]
### Application

YouTube

### Question description

What means browse id? I need to translate it some way, but for translation i need to know what is it

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Also what is "more drawers"?
![Screenshot_20231128_224523_Chrome](https://github.com/inotia00/ReVanced_Extended/assets/110785596/8fb4af4c-9ec7-4ad2-b67a-0b72876efcf5)

**Comment by inotia00** [comment]
> What means browse id?

This is the value used in YouTube Internal API

Although it is not an officially disclosed value, it is used in various projects to reverse engineer the YouTube Internal API
(e.g. https://github.com/tombulled/innertube#usage)
```
data = client("browse", body={"browseId": "FEwhat_to_watch"})
```

Of course, this value is also used in the Android YouTube app

Since `BrowseId` is a unique value, it is more appropriate not to translate `BrowseId` when translating


> Also what is "more drawers"?

these are "more drawers"
![More_Drawer](https://github.com/inotia00/ReVanced_Extended/assets/108592928/5ff51d84-56a2-4d67-ba76-865bfc04467b)
