### ISSUE TITLE
question: How do I create patch with a specific fix

### ISSUE THREAD

**Issue by MarcoSupper** [inotia00/ReVanced_Extended#1762]
### Application

YouTube

### Question description

Hello i recently made a Ticket [issue 1670](https://github.com/inotia00/ReVanced_Extended/issues/1670). It apparently got fixed in [revanced-patches-v2.196.4](https://github.com/inotia00/revanced-patches/releases/tag/v2.196.4). 
I downloaded the RVX Manager and youtube apk v18.45.43. Tried to patch (v2.201.1 automatic patch version) with the default selected (95 patches). The issue with sponsor segment skipping breaking auto next video still exists. 

2nd try:
Downloaded patches.json from revanced patches v2.196.4. Added the json to "Import patch selection". Select default patches. Patch -> still the same issue.

How do I get the fix into a patch?
Ty in advanced.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
> 2nd try:
> Downloaded patches.json from revanced patches v2.196.4. Added the json to "Import patch selection". Select default patches. Patch -> still the same issue.

You cant use older patch versions in the Manager. The only way to use older patches is with the CLI (and maybe also the RVX builder, I'm not sure)

In order to use older patch versions with the cli, you must use the version of the cli, Integrations, and YT apk that is compatible with the patch version you want to use. More info about how to use the CLI can be found in the [documentation repository](https://github.com/inotia00/revanced-documentation).
