### ISSUE TITLE
bug: Comments or episodes can't be scrolled in fullscreen view if press to swipe option is disabled in gesture settings.

### ISSUE THREAD

**Issue by Juloboy** [inotia00/ReVanced_Extended#178]
### Type

Other

### Application

YouTube 18.01.38

### Bug description

Everything is mentioned in description 

### Steps to reproduce

Step 1 - disable press to swipe feature in gesture settings.
Step 2 - open video in fullscreen view.
Step 3 - open comments or episodes panel in right side being on fullscreen view and try to scroll them.

### Relevant log output

```shell
No logs
```

### Screenshots or videos

![Screenshot_20230127-111857_YouTube](https://user-images.githubusercontent.com/59500988/215022158-0c8ad851-651b-4db6-b574-aade9357c905.png)

### Solution

Enabled press to swipe feature is solving this issue.

### Device Environment

Android 12, Crdroid ROM

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Fortunately, it's a bug that reproduces on my device.

Precisely, it is reproduced when either the brightness gesture or the volume gesture is set to off, regardless of the press to swipe values.

The swipe gesture has been rewritten by the ReVanced Team, but there are still minor bugs

Reported issues will be fixed in the next release

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.156.4
