### ISSUE TITLE
bug(YouTube/Theme): Theme is not applied in search results

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#1820]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v18.45.43

### Bug description

When searching something YouTube provides some categories such as `People also watched`, followed by `For you`, `Previously watched`, `From related searches` and `Latest from (Whatever channel you searched)`. But these are showing up in a grey color and are not following the theme patch.
Issue:
![Screenshot_20231213_000208_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/f06ddcee-6d35-473d-b8f0-6f008ad63b57)
![Screenshot_20231213_000216_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/a9a693ed-cd31-48db-9d37-4927c6836641)
![Screenshot_20231213_000221_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/a92cb028-fac0-439e-b33f-db71d4713b44)
![Screenshot_20231213_000232_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/e2e2e3f9-6776-43bd-8c06-0c5ba346d4a9)
![Screenshot_20231213_001723_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/117499019/01dc577e-3f10-4456-91e6-6a4d13d863b7)

The issue isn't present in ReVanced YouTube running on the same version of YouTube.
In ReVanced YT:
![Screenshot_2023-12-13-14-01-24-486_app revanced android youtube~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/08a357d3-24ad-45d9-ba90-923929fe486a)
![Screenshot_2023-12-13-14-01-28-491_app revanced android youtube~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/ef9e6bc7-cb13-49f8-aed4-81f50d1eb103)
![Screenshot_2023-12-13-14-01-43-807_app revanced android youtube~2](https://github.com/inotia00/ReVanced_Extended/assets/117499019/f531eb4d-b524-4866-b01c-adf49809ee18)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This issue is reproducible only if all of the following conditions are met:

Condition 1. Using YouTube v18.43.45+.
Condition 2. Using Google account which A/B tests have been applied.
Condition 3. Disabled `Spoof app version` setting.

This issue cannot be solved by simply adding unsupported colors.

This is because the same color is used in many different layouts, including the button container.

With our current method we cannot apply a theme only to search results.

The following is a temporary solution:

Method 1. Patch to YouTube v18.42.41 or earlier.
Method 2. Patch YouTube to v18.43.45 or later, and spoofing app version to v18.42.41 or earlier via `Spoof app verison` setting.

**Comment by inotia00** [comment]
This issue appears to be A/B tests terminated on the server side.
If this issue reproduces in the future, please open an issue again.
