### ISSUE TITLE
bug: YT - Shorts not getting refreshed

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#1833]
### Type

Other

### Tools used

rvx-builder

### Application

YT v.18.45.43

### Bug description

YT shorts are not getting refreshed after latest patches after patching with 2.205.1 or later patches. I don't know whether it is a problm from my side or it is there.

And also, shorts are being repeated even after clean installing also. It is working fine on stock YT like shorts getting refreshed on every restart of app.

### Error logs

```shell
...
```

### Solution

...

### Additional context

Screen Record --

https://streamable.com/m1ogzd

### Device Environment

Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Exclude patches one by one until the issue is not reproduced.
And please let me know which patch is the cause of the issue

**Comment by Turhvjbufv** [comment]
One by one can take quite the time, do binary search

**Comment by Vipin2003** [comment]
I will do it after completing my semester exams which are overing next week.

**Comment by inotia00** [comment]
> One by one can take quite the time, do binary search

I know this will take a long time

The method of excluding patches one by one and finding out which patch is the cause is a method that devs also use to reproduce or resolve issues

Also, when dev releases a new patch, I compile in more environments than you might think
(I've done thousands of compilations or patches so far for reverse engineering and testing)

OP did not provide which patch caused it
Also, this issue does not reproduce on the dev's side

So I'm just asking for additional information that's reasonable

**Comment by Vipin2003** [comment]
> I know this will take a long time
> 
> The method of excluding patches one by one and finding out which patch is the cause is a method that devs also use to reproduce or resolve issues
> 
> Also, when I releases a new patch, I compile in more environments than you might think (I've done thousands of compilations or patches so far for reverse engineering and testing)
> 
> OP did not provide which patch caused it Also, this issue does not reproduce on the dev's side
> 
> So I'm just asking for additional information that's reasonable

I don't know but after switching to tablet layout and playing shorts and then returning again to phone layout fixed it for me. Check whether it triggers it or not.

Bcoz after a clean install with default settings, the shorts get stuck like the issue, but switching b/w tablet and phone layout fixed it. Please check this at your end too.

**Comment by inotia00** [comment]
https://github.com/ReVanced/revanced-patches/issues/2521

I am mentioning this because it is believed to be a similar issue.

`Spoof app version`, `Enable tablet layout` are all `Experimental Flags`

Just stop using these `Experimental Flags`

I do not provide any fixes related to `Experimental Flags`

**Comment by Vipin2003** [comment]
> [ReVanced/revanced-patches#2521](https://github.com/ReVanced/revanced-patches/issues/2521)
> 
> I am mentioning this because it is believed to be a similar issue.
> 
> `Spoof app version`, `Enable tablet layout` are all `Experimental Flags`
> 
> Just stop using these `Experimental Flags`
> 
> I do not provide any fixes related to `Experimental Flags`

I never used Experimental Flags. I'm just checking what tablet layout does. After switching to tablet layout from phn layout, Shorts have error. But after returning back to phn layout fixed it completely. Well, No issue.
