### ISSUE TITLE
bug(YouTube): Default settings appear in `import/export as text` menu

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1882]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YT 18.45.43
Patches v2.210.1

### Bug description

Some settings info appears in the `Import/Export as text` menu even when they are set to their default values. These settings get removed from the import/export menu when they are set to their non-default values.

The settings that this occurs for are:

* Spoof player parameter
* Enable save playback speed
(I'm assuming that the swipe brightness value is not a bug, or it at least has no formal default value)

![SmartSelect_20240104_100538_ReVanced Extended](https://github.com/inotia00/ReVanced_Extended/assets/84587632/b70ca12c-3076-4079-b4b2-44e15d751bcc)

**Steps to reproduce**

1. Do a clean install of a 18.45.43 apk with all or default patches
2. Go to Settings > ReVanced Extended > Miscellaneous > Import/export settings > Import/export as text.

### Device Environment

Android 13
Samsung oneui 5.1
Non-root

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Some patches cannot specify default values due to limitations in their implementation methods.

For example, there are bugs like this due to limitations in the patch's implementation method: https://github.com/inotia00/ReVanced_Extended/issues/1385

To solve this, I changed the app to override the default values of some settings when first installed.

The settings you reported correspond to the values being overridden.

Therefore... this issue is an issue that cannot be resolved.
