### ISSUE TITLE
Why are some patches non-default?

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#1889]
### Application

Other

### Question description

I'm hoping to PR to help improve the patch descriptions, similar to [this PR](https://github.com/ReVanced/revanced-patches/pull/2519). Please let me know if you do not want this PR or if there is a deadline.

In an effort to be informed before working on these patch description changes, I'd like to understand why some patches are not part of the default set. 

I'm guessing the reason for many will be either because they are non-toggleable or because they are unstable. Sorry that many of these are asked out of ignorance. I'm too lazy to test 😭

**YouTube patches**

1. Add splash animation
2. Disable landscape mode
3. Enable debug logging
4. Enable song search
5. Hide animated button background
6. Hide voice search button
7. Shorts outline button

**YT Music patches**

1. Disable overlay filter
2. Enable debug logging
3. Hide double tap overlay filter
4. Hide voice search button
5. Replace cast button

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Enable song search non-defalut because it is compatible only with 18.30.37+, but RVX supports 18.25.40 ~ 18.29.38 versions too

**Comment by KobeW50** [comment]
> Enable song search non-defalut because it is compatible only with 18.30.37+, but RVX supports 18.25.40 ~ 18.29.38 versions too

Oh, I didn't realize that. I thought that even default patches will need to be manually included if you aren't using a supported version for that patch. Thanks

**Comment by inotia00** [comment]
You can download the source code for revanced-patches and then check which patches are excluded by default by searching for the `use = false` keyword with a utility such as [findinfiles](https://github.com/toolscode/findinfiles/releases/latest)

The list of patches excluded by default is as follows:

YouTube
==
1. Add splash animation
: Since this is adding a feature that has been deprecated by Google, it has been excluded by default.
2. Disable landscape mode
: Since the patch is quite unstable, it has been excluded by default.
3. Enable debug logging
: If you include this patch in rvx-builder, a warning dialog will be displayed.
4. Enable song search
: This patch is only compatible with YouTube v18.30.37+.
5. Hide animated button background
: There is no on/off toggle in settings, this is a patch for some users who need it.
6. Hide double tap overlay filter
: There is no on/off toggle in settings, this is a patch for some users who need it.
7. Hide player button background
: There is no on/off toggle in settings, this is a patch for some users who need it.
8. Hide voice search button
: There is no on/off toggle in settings, this is a patch for some users who need it.
9. MaterialYou
: There is no on/off toggle in settings, this is a patch for some users who need it.
10. Premium heading
: There is no on/off toggle in settings, this is a patch for some users who need it.
11. Shorts outline button
: There is no on/off toggle in settings, this is a patch for some users who need it.

YouTube Music
==
1. Disable overlay filter
: There is no on/off toggle in settings, this is a patch for some users who need it.
2. Enable debug logging
: If you include this patch in rvx-builder, a warning dialog will be displayed.
3. Enable old player layout
: This patch is only compatible with YouTube Music v6.21.51 ~ v6.29.58
4. Hide double tap overlay filter
: There is no on/off toggle in settings, this is a patch for some users who need it.
5. Hide voice search button
: There is no on/off toggle in settings, this is a patch for some users who need it.
6. Replace cast button
: Since the patch is quite unstable, it has been excluded by default.

Reddit
==
1. Custom branding name Reddit
: The way this patch is applied varies depending on the patch method. So it has been excluded by default.
2. Change package name
: The way this patch is applied varies depending on the patch method. So it has been excluded by default.
