### ISSUE TITLE
feat(YouTube Music/Hide layout components): add `Hide settings menu` setting

### ISSUE THREAD

**Issue by VrtxDesign** [inotia00/ReVanced_Extended#1899]
### Application

YouTube Music

### Feature description

Please consider adding this in both RVX and RVX Music

![Screenshot_20240111-091349](https://github.com/inotia00/ReVanced_Extended/assets/69076256/93f147c5-3854-4cc4-80a0-98286033813b)

I want to hide some elements among these.

### Motivation

Because of feels a lot clutter to me.

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This patch will be implemented in YouTube Music soon.

The RVX Settings implemented in YouTube Music are integrated into the YouTube Music settings due to limitations in the patch structure.

In other words, the `Hide settings menu` setting implemented in YouTube Music can hide not only the YouTube Music settings but also the RVX Settings.

This is the difference from the `Hide settings menu` patch implemented in YouTube, and this will be indicated in the summary of the settings.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.3)

**Comment by Aryan-Chauhan** [comment]
Since "General" is only matching word in `stock settings` and `RVX settings`, can a fix be expected from your side?

**Comment by inotia00** [comment]
No, that is an issue that cannot be fixed

That is why I marked it as an issue that occurs on both YouTube and YouTube Music in issue https://github.com/inotia00/ReVanced_Extended/issues/2043
