### ISSUE TITLE
question: What can you say about this idea?

### ISSUE THREAD

**Issue by odkate** [inotia00/ReVanced_Extended#1966]
### Application

YouTube

### Question description

https://github.com/anddea/revanced-patches/issues/441

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Spoof player parameter patch has been removed

This is because in the `ANDROID` client, if the appropriate DroidGuard result is not included, the server side responds with the video id of `the following content is not available on this app`

Please refer to the comments in the commit for more details: https://github.com/inotia00/revanced-integrations/commit/67c5839c8666b6610cbca001e9322635c8411791

**Comment by odkate** [comment]
> Spoof player parameter patch has been removed

this parameter used to be spoofs the sponsored video player? I thought it was spoofed the Shorts player.
