### ISSUE TITLE
bug (YT) : Time stamp & Overlay Buttons are not on the same line.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#1996]
### Type

Cosmetic

### Tools used

Revancify

### Application

Patches v4.8.0-dev.5

Integrations v1.9.0-dev.4

### Bug description

Either the time stamp's position should be moved up a bit or overlay buttons' position should be moved down a bit.
![Screenshot_2024-05-11-22-28-20-48_a9acfd2263b6b7a65bf2540b0d9449ca](https://github.com/inotia00/ReVanced_Extended/assets/91815107/cf1f4b93-a1a5-4b1a-852c-b229872d6761)

### Error logs

```shell
No logs.
```

### Solution

Time stamp & overlay buttons should be on the same line.

### Additional context

No additional context.

### Device Environment

Realme 7 Pro, Realme UI 3.0 (Android 12).

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The bottom padding of the timestamp and overlay button differs slightly depending on the device, so the `WiderBottomPadding` option exists in the patch options. https://github.com/inotia00/ReVanced_Extended/issues/1995

The default value of the `WiderBottomPadding` option is `false`, which can be changed to `true` to resolve the issue.

The `WiderBottomPadding` option was added because a similar bug had already been reported in the past, so closing issue.
