### ISSUE TITLE
suggestion (YT) : Integrate `Change Header` patch from ReVanced to ReVanced Extended.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2029]
### Application

YouTube

### Suggestion description

Hello!

Kindly integrate the `Change Header` patch from ReVanced to ReVanced Extended.

Pull request link: https://github.com/ReVanced/revanced-patches/pull/2512

Commit link: https://github.com/ReVanced/revanced-patches/commit/75f785d1ef6026cbbdf7073c10aace1b28d93a30

Thanks!

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
High-resolution logo image is required to merge patches.

**Comment by Aryan-Chauhan** [comment]
> High-resolution logo image is required to merge patches.

I cannot understand why high-resolution logo image is required to merge patches.

I wasn't requesting for some preset headers.

I will make my own header design and provide the path to those PNGs (this is what I currently do in anddea's RVX, because it has this patch).

![ResizedImage_2024-05-16_10-52-27_1261.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/7963818c-5f90-479b-a1b4-9a12831d88e5)

![Screenshot_2024-05-16-10-59-07-35_91a936403af6fae783b1a226bd5fdf5c.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/de01dd21-2016-4cfd-86b8-99da6e18c57a)

![Screenshot_2024-05-16-10-58-49-85_91a936403af6fae783b1a226bd5fdf5c.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/7b3c6a0f-61b1-4bf2-a646-f890d8bf4168)

![Screenshot_2024-05-16-10-59-55-49_91a936403af6fae783b1a226bd5fdf5c.jpg](https://github.com/inotia00/ReVanced_Extended/assets/91815107/aa5bcbcf-6665-463a-b6bf-0ca6eb91da03)

**Comment by inotia00** [comment]
ReVanced also changes to the [default header](https://github.com/ReVanced/revanced-patches/blob/main/src/main/resources/change-header/revanced/drawable-xxxhdpi/yt_wordmark_header_light.png) value if no configuration options are entered.
This is what I'm talking about.

To implement this, a high-resolution custom header must be provided that supports all resolutions.

**Comment by n1cKz1** [comment]
> Additionally, a valid method that does not conflict with existing `Change YouTube header` settings should be provided.

One way I can think for that to be resolved, perhaps since the premium header on YouTube is named differently than the original header (non premium is `yt_wordmark_header` and premium `yt_premium_wordmark_header`) the change header patch could be tweaked to also replace the premium header along with the non-premium header, and thus being able to switch between 2 custom headers (non-premium & premium) with the change YouTube header setting. Of course this might be more trouble than it's worth though.

**Comment by inotia00** [comment]
The default header value has been added as [PR](https://github.com/inotia00/Revanced-patches/pull/55) is merge.

If I add this with a new patch, there may be conflicts with the existing patch.

So, instead of adding a new patch, I will include it in the patch option of the `Custom branding icon YouTube` patch.

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1-dev.1)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
