### ISSUE TITLE
bug: Does not shows higher resolution when videos in 60fps, only shows up to 480p

### ISSUE THREAD

**Issue by NichirinSword** [inotia00/ReVanced_Extended#2049]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patch v4.8.0 dev-6
Integration v1.9.0 dev-5

### Bug description

With device dimension patch enabled, when videos in 60 fps, resolution shows only upto 480p although it is available in higher resolution like 4k. With device dimension patch disabled, video shows in 1080p with 60fps.

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is related to the issue https://github.com/inotia00/ReVanced_Extended/issues/1954
If the correct droidguard results and potoken are not fetched, the valid video format will not be fetched and the maximum resolution will be limited.

Since it appears to be a duplicate issue, closing the issue.

**Comment by NichirinSword** [comment]
This problem only occurs for 60 fps videos. Other videos works normally, shows all the available video format. And also I don't have any buffering issue in this phone, so i didn't activate any spoof video stream or test patch. It only occurs when videos in 60 fps and device dimension patch is enabled.

**Comment by inotia00** [comment]
1. The `Spoof device dimension` setting only serves to spoof the device's screen resolution as having the maximum resolution.
: As a side effect, 2160p resolution may be unlocked.
If the server side does not check the video resolution information based on the device's screen resolution, 2160p resolution is still not provided.
This is why the name of this setting is `Spoof device dimension`, not `Unlock 2160p video`.

2. `Spoof device dimension` setting has side effects and may no longer be usable due to server-side changes at any time.
: For this reason,`Spoof device dimension` setting is specified as an `Experimental Flags` in RVX settings.
The settings included in the `Experimental Flags` have a very high possibility of causing bugs, and are provided on the premise that the user will be aware of them and use them, so bug reports are not valid.

**Comment by NichirinSword** [comment]
Okay, I understand now. Thank you.
