### ISSUE TITLE
bug: Download action button & Swipe up full screen

### ISSUE THREAD

**Issue by sr-shishir** [inotia00/ReVanced_Extended#2077]
### Type

Other

### Tools used

RVX Manager

### Application

App version: 19.20.34
Issue occurs that mentioned in the image.

### Bug description

![20240526_221937](https://github.com/inotia00/ReVanced_Extended/assets/139035194/9d6f83ef-862b-4153-a0fd-4cf161f42bac)
The swipe up full screen is a very serious issue. Also the download action button issue. Hope you’ll fix it in the next update.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
`Override download action button` is an experimental flag.
The `Experimental Flags` has a very high possibility of causing bugs and cannot be fixed.
Therefore, this setting is provided on the premise that the user will use it knowing that bugs will occur.
If you experience bugs, just stop using it.

Not working `Swipe up to fullscreen` is also a side effect of the `Spoof client` patch.
Since this also cannot be fixed, it is designated as an `Experimental Flags`.

Since all bugs in `Experimental Flags` are impossible to fix, I listed them all in the Github issue, release note, and settings summary, but I don't know why people are asking about this.
