### ISSUE TITLE
question: Malicious patches you are releasing

### ISSUE THREAD

**Issue by aicynide** [inotia00/ReVanced_Extended#208]
### Application

YouTube

### Description

Commit is 3 weeks old and you are releasing patches daily. Actuallt you build and upload yourself. You are not open. You aren't transparent.  Its contains trackers. Don't hide the fact . I know why you don't use github actions to release patch or submit pull request revanced team. You are biggest scammer sketchy. More harmful than Instander, X-manager. You upload patch daily but git commit in patch repo is 3 week old

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
bruh.. You are misunderstood

'Updated 3 weeks ago' is a [main branch](https://github.com/inotia00/revanced-patches) , which is used to leave a Pull Request in the official revanced-patches repository

Therefore, main branch is no longer used

The branch that I actually use is a [revanced-extended branch](https://github.com/inotia00/revanced-patches/tree/revanced-extended), which is always updated.

From August last year to yesterday, You can check hundreds of commit history I added

You can create a jar file that I distribute by clone and build according to the guide provided by the official [revanced/revanced-documentations](https://github.com/revanced/revanced-documentation/blob/main/docs/revanced-development/1_setup_development_environment.md#2-%EF%B8%8F-build-from-source)

There is no GitHub Actions build history because I did not set an environment for using Github Actions

I have been releasing all commit history from August last year to yesterday.

Those who doubt me without searching enough like you always make me tired and make it no longer want to continue development.
