### ISSUE TITLE
question: why was "Quick actions top margin" limited to 32 from original 64?

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2086]
### Application

YouTube

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The `Quick actions top margin` value format provided in previous RVX patches was `raw` value rather than `dip`.
Therefore, incorrect margins were applied depending on the resolution of the device.

Starting with revanced-patches-4.7.1, the `dip` value is applied instead of the `raw` value, thus limiting the maximum margin to 32dip.

32dip has more margin than using 64 as the raw value.
