### ISSUE TITLE
suggestion (YT) : Is it possible to add some padding on the comments bar to make it symmetrical?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [inotia00/ReVanced_Extended#2104]
### Application

YouTube

### Suggestion description

When `Hide Preview Comment` is turned on, the comments bar looks like the following, so it is requested to add some padding on the bottom area, to make it look symmetrical.

![Screenshot_2024-05-31-13-16-36-33_fe557b5c831afa8eecca413bd340ebe7](https://github.com/inotia00/ReVanced_Extended/assets/91815107/2b5cb35d-0c4d-4392-9869-623d2e092fd9)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
No, that is not possible.
Most layouts on YouTube are LithoView.
Since Litho uses a declarative approach to building UI, you can't change a property on a View in-place.
In ReVanced, the Layoutparams of the View cannot be changed when hiding the LithoView, so simply replacing it with `EmptyComponent` is used.
