### ISSUE TITLE
Absence button disable swipe-to-switch video whith anddeas patches

### ISSUE THREAD

**Issue by Gubbbka** [inotia00/ReVanced_Extended#2149]
### Application

YouTube

### Question description

4 days ago i met in anddeas version that by swiping up or down i can switch video. I wanted to disable this but not found any buttom related to that.  In anddeas releases changelog also isnt info about it, so i thought its bug. 

But in your changelog i read its your new feater, and in your settings this buttom was present.
So why without anddeas work your new feater auto merged to his version, but buttom in settings not appeared in his settings? 
PS. After i opened this bug on his page, he suggested reopen this on your issues center

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I didn't fully understand the content you wrote, but I will answer you as much as I understand

1. `Enable swipe to change video` setting has been added to [revanced-patches-4.9.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.9.1)
2. `Enable swipe to change video` setting is added only to users who patched YouTube 19.19.39+ (Google added this code in YouTube 19.19.39)
3. I'm not sure because I didn't look into Anddea's repository in detail, but he probably hasn't merged all the commit yet
