### ISSUE TITLE
feat: Toggle to have a swipe control screen size to be exclusive for the sound/brightness swipe gesture

### ISSUE THREAD

**Issue by ArcherLegend** [inotia00/ReVanced_Extended#2151]
### Application

YouTube Music

### Feature description

Currently the swipe controls for brightness and sound can be costumised with the "swipe overlay screen size" setting and the "press-to-swipe gesture".

If possible there should be an additional setting (which should be separeted from the "swipe overlay screen size") to set a screen zone percentage to only pick up the swipe gesture for brightness or volume rather than having that area also working for the press for double playback speed / swipe horizonally to move the timeline.

### Motivation

This feature should be implemented because when using the "press-to-swipe gesture" to control sound and brightness often times the Youtube app activates the double playback speed (or scrub across the timeline depending on what you have set up in Revanced settings) and it makes using the swipe controls for audio/brightness very tedious to trigger at times.

Being able to set a separate screen percentage deadzone where the press-to-swipe gesture ONLY triggers the audio/brightness controls would completely solve the inconvenience.

[This request was originally posted on anddea's repo](https://github.com/anddea/revanced-patches/issues/111) but it was closed as he cannot make it work with the current forks of inotia00's RevancedExtended

### Acknowledgements

- [ ] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I haven't accepted Feature Requests for YouTube anymore since September 2023.

The reason for this is as follows:
1. Since 2022, too many patches and custom settings have been added to RVX. This made the code maintenance too hard.
2. Unlike YouTube Music, YouTube's layout has been fully migrated to litho from 2023, so reverse engineering or patch implementation have become very difficult.
3. From 2024. Google began to add experimental flags aggressively. This also interferes with new patch implementation.

For this reason, I only accept patch requests for YouTube Music or Reddit.

If you want to open a feature request for YouTube, move to the repository of ReVanced Team.

**Comment by Aryan-Chauhan** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/1975
