### ISSUE TITLE
bug: Check internet Connection

### ISSUE THREAD

**Issue by JakobHunterek** [inotia00/ReVanced_Extended#2163]
### Type

Error at runtime

### Tools used

Revancify

### Application

Youtube 19.21.40

### Bug description

I can't add my account to youtube let alone connect to it

### Error logs

```shell
It shows the check internet connection
```

### Device Environment

Android 8 Samsung Experience 9.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This failed to get login information from a Google account registered with GmsCore for some reason

A typical example is _when you change the password of your Google account_

Workarounds are as follows:
1. Go to Account Settings in System Settings
2. Remove Google accounts registered with GmsCore
3. Re-register your Google account in GmsCore

Even if you follow this method, if the issue is not solved...
1. Uninstall RVX and GmsCore
2. Install GmsCore first
3. Install RVX
