### ISSUE TITLE
question (YT/YTM): Cairo-related questions

### ISSUE THREAD

**Issue by GucekPL** [inotia00/ReVanced_Extended#2184]
### Application

Other

### Question description

Hi, I have questions:

1. Is that already know what **`Cairo Update`** will include for the YT and YTM applications?
2. Will there be more Cairo-related things introduced in RVX?
3. Why translucent navbar only works for Android 12 and above?

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
> 1. Is that already know what **`Cairo Update`** will include for the YT and YTM applications?

Nah I'm just one user, so I don't know everything either 😅

Summarizing what has been revealed so far and what I have confirmed:

Cairo theme has been applied to Navigation bar, Toolbar, Splash animation, Seekbar, Notification dots, and settings

As the YouTube version increases, the number of supported Cairo themes increases little by little

Cairo theme still relies on A/B testing

Therefore, most Cairo themes can only be used with Google accounts with A/B testing applied, but some Cairo themes can be force enabled or disabled on the client side
(e.g. [Cairo settings](https://github.com/inotia00/ReVanced_Extended/issues/2099) and [Cairo seekbar](https://github.com/inotia00/ReVanced_Extended/issues/2178) can be changed on the client side, but Cairo splash animation for YouTube and [Cairo navigation bar](https://github.com/inotia00/ReVanced_Extended/issues/2169) cannot be changed on the client side)



> 2\. Will there be more Cairo-related things introduced in RVX?

Cairo themes that can be force-enabled on the client side will be implemented in an RVX patch



> 3\. Why translucent navbar only works for Android 12 and above?

For some reason the translucent navbar implemented by Google checks whether the user is using Android 12+
Probably because it uses APIs that are only used in Android 12+ (like MaterialYou)

**Comment by GucekPL** [comment]
Thanks you so much!!
