### ISSUE TITLE
suggestion: Make RVX Manager's `Data sources` section like ReVanced Manager

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2227]
### Application

Other

### Suggestion description

Although RVX Manager is based on ReVanced Manager, the `Data sources` section is different.
**ReVanced Manager:**
![Screenshot_20240706_170005_ReVanced Manager](https://github.com/inotia00/ReVanced_Extended/assets/127908708/dda9a2bf-3f85-4d0b-9f9d-88e3e0aa20b7)
**RVX Manager:**
![Screenshot_20240706_165955_RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/127908708/3783e83d-e4da-47b9-b384-0daef03e18f8)
On ReVanced Manager when `Use alternative sources` is disabled it uses the default source and when it's enabled it uses the alternative one.

The requested change will make it much faster for those who use a different source because you won't have to manually type the other source or the default source every time when you need to use it, but you will just need to enable/disable the toggle just like on ReVanced Manager.
**Note:** the default source should changed to the RVX's one.

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This setting has been removed because it is literally not needed.

Since RVX does not provide its own API, RVX patches can only be used when the `Use alternative sources` toggle is always ON.

If the user changes the `Use alternative sources` toggle to OFF, ReVanced's patch (original) will be used, which may cause confusion for the user.

For this reason I have removed the `Use alternative sources` toggle and have no plans to restore this setting.
