### ISSUE TITLE
suggestion: change the `Change version code` patch to a universal patch

### ISSUE THREAD

**Issue by federicogith** [inotia00/ReVanced_Extended#2229]
### Application

YouTube

### Suggestion description

That patch can be really useful because it allows to downgrade if an update is messed up

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [X] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The `Change version code` patch is also implemented in the RVX patch, but is only targeted at Reddit.

The reasons for this are as follows:

1. The `Change version code` patch does not work in the root environment.

Therefore, it cannot be used on YouTube and YouTube Music in the root environment.

2. The `Change version code` patch is not required for YouTube and YouTube Music in a non-root environment.
(Because non-root apps are not shown in the update list of PlayStore)

For the `Change version code` patch to target YouTube or YouTube Music, more reasonable motivation is needed.

**Comment by KobeW50** [comment]
> For the `Change version code` patch to target YouTube or YouTube Music, more reasonable motivation is needed.

Users may want to downgrade YT/YTM if they discover an issue in a newer version. 

But currently, the only thing that can be done is to export the settings config, uninstall YT/YTM RVX, and patch and install an older version where the issue doesn't exist. 

It would be simpler if a user can just apply the Change version code patch and install the older version (without the issue) on top of the version that had the issue.

**Comment by inotia00** [comment]
> It would be simpler if a user can just apply the Change version code patch and install the older version (without the issue) on top of the version that had the issue.

It makes sense

If the `Change version code` patch is implemented as a universal patch, issue https://github.com/inotia00/ReVanced_Extended/issues/2211 will also likely be closed

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.2)
