### ISSUE TITLE
About spoof client

### ISSUE THREAD

**Issue by Gubbbka** [inotia00/ReVanced_Extended#2238]
### Application

YouTube

### Question description

My yt works without spoof client (i use revanced gms core, with other gms core i have buffering). In rvx chat i  met a few people who also have working yt without spoof but with another gms core (seem like gms core version individual for everyone(?)

All other chatters must turn on spoof client to fix buffering issue anyway. I tried to get at least a little logic there but cant. 

From what it depend? Or this is really full randomized thing and we just lucky? 

Or yes is there any hope to put away side effect of spoof client, or spoof client at all in future for everyone?  
Its maybe biggest question which i try to undertand 2 month

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
![droidguard](https://github.com/user-attachments/assets/9c22bab6-ede0-42d4-9fa0-e4a1396a686d)


Starting in 2023, Android YouTube clients will require a [valid PoToken to play videos](https://github.com/microg/GmsCore/issues/1870).
Because this is a server-side change, all clients that use the YouTube API are affected.
(Other open source YouTube clients besides ReVanced are also affected.)

In other words, if GmsCore's DroidGuard's VM (com.google.ccc.abuse.droidguard.DroidGuard) does not generate the correct DroidGuardResult, users will experience playback issues.

Fortunately, [microg/GmsCore implemented PoTokenService](https://github.com/microg/GmsCore/issues/2253) on December 22, 2023, and the playback issue was resolved by ReVanced Team releasing [ReVanced/GmsCore](https://github.com/ReVanced/GmsCore/releases/tag/v0.3.1.1.240913) fork on March 26, 2024.

GmsCore's DroidGuard's VM (com.google.ccc.abuse.droidguard.DroidGuard) is updated approximately every two weeks by Google servers.

**The current GmsCore does not support the new DroidGuard VM, so if users reinstall GmsCore after June 2024, they will experience playback issues.**

**If users installed GmsCore between March 2024 and June 2024 and have never uninstalled it, they will not experience playback issues.**

In this case, the user must spoof the client to bypass the playback issue.

**Comment by Gubbbka** [comment]
And last one, has it chance to be fixed in the future for all users? Or it impossible to say due unpredictable google's action after all

**Comment by inotia00** [comment]
It seems very unlikely, but if the MicroG Team supports the new DroidGuard VM, the Spoof client patch will not be needed
