### ISSUE TITLE
suggestion: Search channel

### ISSUE THREAD

**Issue by Spaceshiprace** [inotia00/ReVanced_Extended#2239]
### Application

YouTube

### Suggestion description

Its on YouTube web version but not on the app
![Screenshot_2024-07-12-22-33-34-107_org mozilla firefox_1_1](https://github.com/user-attachments/assets/a6eb9d9a-efed-4d8d-bbad-24409079012a)

### Acknowledgements

- [X] This issue is not a duplicate of an existing suggestion.
- [ ] This is not a feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I haven't accepted Feature Requests for YouTube anymore since September 2023.

The reason for this is as follows:
1. Since 2022, too many patches and custom settings have been added to RVX. This made the code maintenance too hard.
2. Unlike YouTube Music, YouTube's layout has been fully migrated to litho from 2023, so reverse engineering or patch implementation have become very difficult.
3. From 2024. Google began to add experimental flags aggressively. This also interferes with new patch implementation.

For this reason, I only accept feature requests for YouTube Music or Reddit.

If you want to open a feature request for YouTube, move to the [repository of ReVanced](https://github.com/ReVanced).
