### ISSUE TITLE
bug(YouTube/SponsorBlock): the new SponsorBlock segment popup doesn't show minutes in the timestamp

### ISSUE THREAD

**Issue by NoMorePizza** [inotia00/ReVanced_Extended#2263]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.16.39
Patches v4.10.2

### Bug description

When timing a new segment, minutes are missing from the timestamp. It's just a visual bug, actual timestamp has minutes correctly in place, and segments will work fine. Manually editing segment timing shows the correct time, so no issues there.

In this popup timestamp is 00:38:931 when it should be 02:38.931.
![20240720_064824](https://github.com/user-attachments/assets/b284fe30-482b-41b2-903a-320dd092b758)

And this timestamp is 01:33:393 and it should be 01:15:33.393.
![20240720_064849](https://github.com/user-attachments/assets/ec3613cb-ffb6-4a6f-bc86-b88373a76d30)

Setting timing manually shows the correct time.
![20240720_071635](https://github.com/user-attachments/assets/c737cd09-d421-40f2-9a4b-d1be36634d69)

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
**Process for reproducing the issue**

1. Include the `SponsorBlock` patch.
2. Turn on `Show create new segment button` in SponsorBlock settings.
3. Play any video and go to a time between 10 and 60 minutes. (e.g. 00:12:34)
4. Click `Create new segment button`.
5. Click `Adjust button` (◉).
6. The timestamp is displayed as `00:34.000` instead of `12:34.000`.

**Additional context**

RVX's SponsorBlock follows ReVanced's code exactly.
So this issue can also be reproduced in ReVanced.

Commit https://github.com/ReVanced/revanced-integrations/commit/81251f9a34ef9f252ce69b01b40e29480a5add9f# is the direct cause of the issue.

Since this commit, the timestamp has the following format:
[HH:SS:sss](https://github.com/ReVanced/revanced-integrations/blob/7bf43c68965821ca8860a28aa130b99aabfb5d3c/app/src/main/java/app/revanced/integrations/youtube/sponsorblock/SponsorBlockUtils.java#L237)

To resolve the issue, the timestamp must have the following format:
MM:SS:sss

**Comment by inotia00** [comment]
FYI @LisoUseInAIKyrios

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.10.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.3)
