### ISSUE TITLE
bug(YouTube/Flyout menu components): `Download video` not being hidden from feed flyout menu

### ISSUE THREAD

**Issue by 54m4d** [inotia00/ReVanced_Extended#2280]
### Type

Other

### Tools used

RVX Manager

### Application

v19.16.39 - v4.10.3

### Bug description

Hi, when adding `Download video` to the feed flyout menu filter, the `Download video` option does not get hidden. However, other elements, e.g. `Report` etc..., work as expected.

### Error logs

```shell
N/A
```

### Solution

If reproducible, check how `Download video` can be properly targeted and filtered.

### Device Environment

Android 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by Aryan-Chauhan** [comment]
It is working for me.

Can you show screenshot of the page on which it is not working? 

HomeFeed, Subscriptions Tab, Playlists, Search Results or some other place?

**Comment by inotia00** [comment]
It doesn't reproduce on my side.
Please attach a screenshot.

**Comment by 54m4d** [comment]
Hi, for some reason, I'm experiencing a different behavior today: `Loading downloads state...` appears and then disappears after a couple of seconds.

I don't think I consider this an issue anymore, since the element gets hidden anyway. Feel free to close this issue.

<details>
<summary>Added string</summary>
<img src=https://github.com/user-attachments/assets/b46952a7-2aa4-4324-a783-fe2792f0149c>
</details>

<details>
<summary>Bug</summary>
<img src=https://github.com/user-attachments/assets/324c1777-c2ff-4df9-b16b-7a7189b0946f>
</details>

**Comment by Aryan-Chauhan** [comment]
This only appears when you've cold-started the app and eventually it disappears.

**Comment by inotia00** [comment]
It is a bug in the YouTube app to see the `Loading downloads state...` menu instead of the `Download video` menu, not the RVX
(This can also be reproduced on unpatched YouTube)

It is normal that the `Loading downloads state...` menu is not hidden because you only added the `Download video` keyword to `Feed flyout menu filter`

To hide the `Loading downloads state...` menu, simply add the `Loading downloads state...` keyword to the `Feed flyout menu filter`

Copy the following and paste it into the `Feed flyout menu filter`:

```
Download video
Loading downloads state...
```

**Comment by 54m4d** [comment]
Thanks for the info.
