### ISSUE TITLE
bug: IP/Wlan throttling

### ISSUE THREAD

**Issue by MarcoSupper** [inotia00/ReVanced_Extended#2335]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube v19.25.39

### Bug description

Since about 2 weeks RVX keeps buffering since it's not preloading fast enough. Most of the time it's at the start of playing a video. I have to keep closing/reopening the video to be able to play it. Then in the first quarter of the video it sometimes loads so slow that it just keeps buffering than going for like 2 seconds than buffering again. It seems this problem doesn't happen when I use mobile data. And no my internet works perfectly well. I can use it for anything else besides RVX. I have all my spoof clients set to IOS.
Haven't been able to test it with a different wlan yet.
There seems to have been a similar bug recently but that was said to have been patched ~2-3 months ago.

### Device Environment

Android 13

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Support for versions newer than 19.16.39 was rolled back, so bug reports aren't accepted for these versions.

It sounds like client spoofing will fix your issue. Patch one of the currently supported versions and navigate to Settings > ReVanced Extended > Miscellaneous > Spoof client, and enable client spoofing.

Open a new bug report if the issue is still not resolved on a supported version when client spoofing is enabled.

**Comment by MarcoSupper** [comment]
I downgraded to 19.16.39 and the problem still persists. Where are the debug logs located btw.
