### ISSUE TITLE
feat(YouTube Music): rename `Enable Cairo splash animation` to `Disable Cairo splash animation`

### ISSUE THREAD

**Issue by Kantotero** [inotia00/ReVanced_Extended#2366]
### Application

YouTube Music

### Feature description

Just like in RVX, can you please add disable splash animation on app startup. I think this splash animation is new to me, I didn't have this splash animation for awhile and it just popped out, and based on 
[inotia's comment](https://github.com/inotia00/ReVanced_Extended/issues/2354#issuecomment-2323256186) this might be an A/B tests thing

### Motivation

https://github.com/user-attachments/assets/45448ce7-b0eb-463b-b81d-c25ef8eaa359

I get splash animation on app startup when I open my RVX Music. Not really a fan of those. I didn't have the cairo splash animation patch so I don't know why I get the app startup animation

### Acknowledgements

- [X] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is an already implemented patch

1. Include `Enable Cairo splash animation` patch
2. Turn off `Enable Cairo splash animation` in settings
3. Cairo splash animation is forcibly disabled

**Comment by inotia00** [comment]
According to [9To5Google](https://9to5google.com/2024/09/06/youtube-music-animated-splash-screen/), Cairo splash animations have been fully rolled out as of yesterday

Since Cairo splash animations are no longer an A/B test, if you are using **YouTube Music 7.06.54+**, Cairo splash animations are enabled by default

So I think it would be more appropriate to rename the `Enable Cairo splash animation` patch to the `Disable Cairo splash animation` patch
(This is a valid issue, so I will keep it open)

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1)
