### ISSUE TITLE
bug: Voice input causes crash

### ISSUE THREAD

**Issue by AlphaCraft9658** [inotia00/ReVanced_Extended#237]
### Type

Error at runtime

### Application

YouTube 18.04.41

### Bug description

When using the voice search feature in the search bar, the app crashes after the recording stops

### Steps to reproduce

Go to the search bar
Tap onto voice search
Say something
See the crash

### Relevant log output

```shell
No Logs
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please add the environment you tried to patch
(Patches included or excluded, tools that tried to patch)

**Comment by AlphaCraft9658** [comment]
I installed ReVanced Extended directly from the websites without manually patching anything.

**Comment by inotia00** [comment]
It is difficult to provide assistance if information about which environment the patch was applied is missing.

Follow the [documentation](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android))  to proceed with the patch, and if the bug is reproduced, re-open an issue in the prescribed format.
