### ISSUE TITLE
question: Can you please make an updated version of Revanced Extended YouTube? We haven't had one in a while G

### ISSUE THREAD

**Issue by BIackJacks** [inotia00/ReVanced_Extended#2386]
### Application

YouTube

### Question description

Hey G I want to know if you can make a new version of the Revanced Extended YouTube app as the current one is kind of outdated.

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
The [latest patch](https://github.com/inotia00/revanced-patches/releases/latest) has only been out for a week

I rolled back YouTube's support version to 19.16.39 for the following reasons: https://github.com/inotia00/ReVanced_Extended/issues/2241

YouTube 19.16.39 is the version where all patches work normally and no features are broken due to A/B testing

If you patched with the latest patch, you should not have any playback issues
(As of this comment, the latest patch is [revanced-patches-4.13.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.13.1))

If you are having any issues, you are probably using an outdated patch
(just patch again)

Adding support for the new YouTube version is expected in December of this year or January of next year

Adding support for the new YouTube version is expected in December of this year or January of next year, after A/B testing has fully concealed
