### ISSUE TITLE
feat: Rounded corners in video playback

### ISSUE THREAD

**Issue by Joshua64** [inotia00/ReVanced_Extended#2406]
### Application

YouTube Music

### Feature description

![Screenshot_2024-09-26-15-25-07-147_com gof global](https://github.com/user-attachments/assets/2886cf5f-03f1-4641-831b-5d776f5ac3c8)

Rounded corners like the corners in the picture in picture mode

![Screenshot_2024-09-26-15-28-52-272_app rvx android youtube](https://github.com/user-attachments/assets/97a44c37-086e-42b4-9ef3-27f5ca732179)

Is possible to use (or apply) rounded corners to vídeo playback in the portrait mode ? and is possible to apply in full screen mode ? Like one of the rounded corners apps in the Playstore does ?

### Motivation

Better look to videos i guess :)

### Acknowledgements

- [ ] This is not a feature request for YouTube.
- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
I haven't accepted Feature Requests for YouTube anymore since September 2023.

The reason for this is as follows:
1. Since 2022, too many patches and custom settings have been added to RVX. This made the code maintenance too hard.
2. Unlike YouTube Music, YouTube's layout has been fully migrated to litho from 2023, so reverse engineering or patch implementation have become very difficult.
3. From 2024. Google began to add experimental flags aggressively. This also interferes with new patch implementation.

For this reason, I only accept feature requests for YouTube Music or Reddit.

If you want to open a feature request for YouTube, move to the [repository of ReVanced](https://github.com/ReVanced).
