### ISSUE TITLE
bug: Problems with Channel Overview when all Navigations-Tabs expect One are filtered out

### ISSUE THREAD

**Issue by 30b0** [inotia00/ReVanced_Extended#2411]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube 19.16.39 | Patches v4.14.1 (latest)

### Bug description

When opening the List of Subscribed Channels, then entering a Channel that has only one Navigation-Tab, the Overview appears emtpy.

In my Case I filter out everything expect Videos and Playlists. If the Channel doesn't have Public Playlists, only Videos is available. This causes Problem when entering Channels this Way.
![Screenshot_20240928-183308_YouTube](https://github.com/user-attachments/assets/dc2927ed-15a2-4566-bf31-3ee057e6b3f7)

When I don't filter out the "Home" -Tab (or "Community"-Tab) then this Problem doesn't appear, since it now has a second Tab to open on.
![Screenshot_20240928-191929_YouTube](https://github.com/user-attachments/assets/70dbb4c9-0268-4acb-8130-572113a4f508)

When entering the Channel on any other Way, like searching for the Channel in the search or opening a Video and then click on the Channel, it has no Problem when only one Tab is left.
![Screenshot_20240928-183318_YouTube](https://github.com/user-attachments/assets/b0fcb6d5-d6e4-4eec-8073-6df8605b642c)

### Device Environment

OnePlus 9 Pro, Android 14, CrDriod 10.8

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Does the issue persist even after disabling all Custom filters?

**Comment by 30b0** [comment]
Yes, still the same Problem. (Sorry for not testing before the Post)
![Screenshot_20240928-193606_YouTube](https://github.com/user-attachments/assets/10b72202-c2cd-4b27-b727-5889d55d3a77)

But I just noticed after editing the Screenshot and opening YT back up, or after clicking on the Channel Description and going back the Channel Overview loads normally.
![Screenshot_20240928-193641_YouTube](https://github.com/user-attachments/assets/65c9f6f3-6cb7-411f-bd35-d4643ed43db9)

**Comment by inotia00** [comment]
Ah, I thought this was a custom filter issue just from the first screenshot

To conclude, this is not a bug

In the past, there was no `Hide channel tab filter` setting, only `Hide store tab` setting

The `Hide store tab` setting only hid the button in the channel tab list, but the channel tabs were still accessible
(by swiping the channel tab)

Here are the bug reports related to this:
https://github.com/inotia00/ReVanced_Extended/issues/1937
https://github.com/inotia00/ReVanced_Extended/issues/1945

As a follow-up to these bug reports, the `Hide channel tab filter` setting has been added

Since the `Hide channel tab filter` setting actually removes the channel tab, it is closer to the intended behavior to behave as in the screenshot you attached
