### ISSUE TITLE
question: Google Play Protect warning everytime while installing YouTube Music only

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2420]
### Application

YouTube Music

### Question description

Everytime when I'm installing or updating YouTube Music, I'm greeted with the play protect warning. But this isn't the case with YouTube.  So, I'm confused as to what difference is causing Play Protect to flag one app but not the other.
![Screenshot_20241005_191636_Google Play Store](https://github.com/user-attachments/assets/bf1bfafb-1600-4998-badf-9e49b800cc6c)

### Acknowledgements

- [X] This issue is not a duplicate of an existing question.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
There are various reasons why you may see Google Play Protect warnings.

According to the [official docs](https://developers.google.com/android/play-protect/warning-dev-guidance#app_scan_recommended) from Google, this warning is because your app has never been scanned by Play Protect.

Almost all personal builds that are not uploaded to the Play Store are checked by Play Protect before installation.

The reason why you are probably seeing this warning only on YouTube Music, and not on YouTube, is because you have never scanned RVX Music, but have scanned RVX at least once.

If you don't want to see this warning anymore, click `Scan app` to let Play Protect know that RVX Music is safe.

Then, after enough time, Play Protect will recognize RVX Music as a scanned app, and the warning will no longer appear.
