### ISSUE TITLE
bug(YouTube Music - Hide ads): Blank screen at app first start

### ISSUE THREAD

**Issue by YT-Advanced** [inotia00/ReVanced_Extended#2515]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

v7.16.53

### Bug description

Video: https://t.me/revanced_extended_chat/355685

After checking, I can confirm that `Hide fullscreen ads` caused this problem

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
since I can't reproduce the issue on my side, I changed the default setting to off and added information about the issue to the description

reflected in [revanced-patches-5.0.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.0.1)

**Comment by BourgeoisDirk** [comment]
@inotia00, i might know how to reproduce it. It only seems to occur as a new user.
When opening RVX YouTube Music Extended for the first time, it just shows a black screen.

After uninstalling, i installed YouTube ReVanced, this then opened a youtube membership screen, which i closed.
Uninstalled ReVanced, and re-installed RVX Music, and now when running it ends up on the home screen instead of a black screen.
