### ISSUE TITLE
bug: RVX App 19.44.39

### ISSUE THREAD

**Issue by Maxsyss** [inotia00/ReVanced_Extended#2588]
### Type

Error while patching

### Tools used

RVX Manager

### Application

19.44.39 is built using [Inotia00 patches]

### Bug description

An error has appeared on the latest RVX patch. When you try to rewind or skip an ad, the video restarts and starts over.

### Error logs

```shell
-
```

### Solution

-

### Additional context

-

### Device Environment

Android 14, OxygenOS 14.1, OnePlus Nord 4 16/512.

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Exclude patches one by one and report back which patch causes the issue.

**Comment by Maxsyss** [comment]
I don't quite understand how this bug works, so I can't repeat it for clarity. This bug is triggered spontaneously when watching a video.

**Comment by inotia00** [comment]
1. Exclude all patches, include only `GmsCore support` patch and check if the issue is reproduced.
2. If the issue is not reproduced, include patches one by one and check again.
3. If the issue is reproduced, Report back which patch was last included.

You are missing the necessary informations to report the issue, such as the full list of included or excluded patches, the settings you are using, screenshots or videos that can explain the symptoms of the bug, and the exact steps to reproduce the bug.

Please re-open the issue by filling out the form provided.
