### ISSUE TITLE
question: List of all custom filter options?

### ISSUE THREAD

**Issue by Chirronupu** [inotia00/ReVanced_Extended#311]
### Application

YouTube

### Description

Is it possible to gather a list of all custom filter options? 
Or, if there are too many, perhaps only the common / useful ones.

Custom filters I'm currently using: home, chips, related_video, quick_actions

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
No separate full list exists
Check the litho element through debugging and add it there.

**Comment by StradivariusKane** [comment]
> No separate full list exists Check the litho element through debugging and add it there.

Can you please teach me how to do this? Im really interested.

**Comment by KobeW50** [comment]
> > No separate full list exists Check the litho element through debugging and add it there.
> 
> Can you please teach me how to do this? Im really interested.

This page has a large list of components 

https://kazimmt.github.io/RVX-Features/troubleshoot/yt-custom-filters/

**Comment by StradivariusKane** [comment]
Thats not what I asked, I asked inotia to teach me how to use debug feature, it is his patch that he added in the past.

Im allowed to ask questions right?

**Comment by KobeW50** [comment]
> Thats not what I asked, I asked inotia to teach me how to use debug feature, it is his patch that he added in the past.
> 
> Im allowed to ask questions right?

I'm sorry

**Comment by KobeW50** [comment]
@StradivariusKane 

Im not qualified but heres some info. I hope this is helpful

After including the debuging patch and enabling it in the Miscellaneous settings, run this command in ADB (I'm a noob with ADB but theres lots of tutorials out there)

Command for windows: `adb logcat | findstr "Extended" > log.txt`

For Linux: `adb logcat | grep --line-buffered "Extended" > log.txt`

The command is the same for YT and YTM.

You can also use a debugging app on ur device instead of ADB. inotia00 recommended me to use [this one](https://play.google.com/store/apps/details?id=com.dp.logcatapp)

This screenshot shows further instructions for setting up and using the debugging app

![SmartSelect_20230911_162238_Reddit.jpg](https://github.com/inotia00/ReVanced_Extended/assets/84587632/a21b4725-5eb7-4a82-ae56-ce3eb12ea0d3)

**Comment by StradivariusKane** [comment]
Hmm, I dont have a computer so I cant use adb, and I cant download that app because its designed for older versions of android. Can I use termux?

**Comment by inotia00** [comment]
root permissions are required to check logs without ADB
