### ISSUE TITLE
bug: Often times feed doesn't load

### ISSUE THREAD

**Issue by anyujinie** [inotia00/ReVanced_Extended#412]
### Type

Error at runtime

### Application

Version 18.07.35 non-root

### Bug description

I often times encounter situations where the feed doesn't  load. Forcing me to close the app and restart. This only happens with RVX not wirh stock YT. It's very frustrating....

![Screenshot_20230305-183400397](https://user-images.githubusercontent.com/73917917/222976452-2f87beb3-20c2-4750-bc79-250aabdddf88.png)

**Comment by inotia00** [comment]
bug in YouTube, not a bug in Extended.

**Comment by anyujinie** [comment]
> bug in YouTube, not a bug in Extended.

From where do you get this information? Can you please refer me

**Comment by inotia00** [comment]
> > bug in YouTube, not a bug in Extended.
> 
> From where do you get this information? Can you please refer me

You can also reproduce this bug on unpatched YouTube if you use a Google account that allows you to use the new layout.

So, this is a bug that Google needs to fix.

**Comment by inotia00** [comment]
To add a little more technical explanation, YouTube gets the layout related to litho from the server every time the app is opened.

The issue shown in the attached screenshot is reproduced when litho is not yet loaded.

Since litho is used by official YouTube, Google needs to improve the performance of this layout so the issue no longer reproduces.
