### ISSUE TITLE
feat(patch): option to choose browser while opening links externally

### ISSUE THREAD

**Issue by johnconner122** [inotia00/ReVanced_Extended#450]
### Application

YouTube

### Issue

Usually when we click a link, it opens in default browser, provided `open-links-externally` is enabled.

### Patch

This patch should allow user to choose browser while opening links externally. `open-links-externally` can be modified instead of creating a separate patch.

### Motivation

Sometimes we want to use another browser for different links.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by MondayNitro** [comment]
then why do you set defaults? youtube doesnt decide which browser to open the link in, if you wish to have that choice then you should not set a default browser

**Comment by johnconner122** [comment]
> then why do you set defaults? youtube doesnt decide which browser to open the link in, if you wish to have that choice then you should not set a default browser

Newer Android versions force to select default browser.

**Comment by inotia00** [comment]
To get a list of browser apps installed on the device, the YouTube app needs to be able to recognize a specific intent tag (android.intent.category.BROWSABLE) in the browser app's manifest.

But since Android 11 (targetSDK >= 30), there are [restrictions on using package visibility according to Android policy](https://developer.android.com/about/versions/11/privacy/package-visibility) 

In other words, it was changed to the white list method.

To avoid this, you need to lower the app's targetSDK version or add a specific permission to the manual manifest (QUERY_ALL_PACKAGES)

However, with the current YouTube patching method it is not possible to add the permission to the manifest.

More precisely, it is possible in non-root builds, but impossible in root builds due to the limitations of the patching method.

So.. implementing this is currently completely impossible
