### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by BrilliantlyEducated** [inotia00/ReVanced_Extended#584]
### Type

Error at runtime

### Application

version 18.11.36

### Bug description

the bug hides the information

### Steps to reproduce

go to Settings> About> Open source licenses> Android Support Tools

### Relevant log output

```shell
.
```

### Screenshots or videos

ReVanced Extended

![IMG_20230328_000001](https://user-images.githubusercontent.com/36302515/228070261-8e0e5e43-ebb5-41eb-ba96-f76aca85cc07.jpg)

Original

![IMG_20230328_000002](https://user-images.githubusercontent.com/36302515/228070264-60cff0e9-fe4d-45b1-861a-c52fcedc5abb.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unfortunately, there is no plan to fix this issue

**Comment by BrilliantlyEducated** [comment]
what does the optimize-resources do?

**Comment by inotia00** [comment]
Basically, the patch changes to a structure similar to antisplit-apk.

base.apk + split.config_xxhdpi.apk + (library) + (language config) = `optimize-resources` patched app

In addition, it also removes some kind of 'dummy files', such as license activity, that are rarely used in practice and take up a lot of space.

It is a pretty fatal issue that makes the license activity bounce, but it is not a fatal issue that the contents of the open source license are not displayed, so it is said that there is no plan to fix it.
because it was intended

So if you often use fairly minor features like open source licenses, just exclude those patches.

**Comment by BrilliantlyEducated** [comment]
thank you for the information
