### ISSUE TITLE
Issue with Videos in YT

### ISSUE THREAD

**Issue by Vipin2003** [inotia00/ReVanced_Extended#589]
### Type

Other

### Application

YT

### Bug description

There is a bug that every played video is played in PIP of the previous Video. I reinstalled it but no solution. Please fix this.

### Steps to reproduce

Just play any video from the home feed.
Now, search for any video and play it.

You will see the issue.

### Relevant log output

```shell
...
```

### Device Environment

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
- YouTube version you tried to patch
- the patches version you used
- Under what circumstances the issue can be reproduced
(included patch and excluded patch list, ReVanced settings backup file)
- Screenshots or screen records related to the issue

If any of these are missing I can't help you
This is because the issue is not reproducible no matter what environment I test it in.

**Comment by Vipin2003** [comment]
I'm trying to upload the files but was not able to upload...not even the settings json file..
