### ISSUE TITLE
feat(patch): disable default playback speed on live stream video

### ISSUE THREAD

**Issue by sleepingiv** [inotia00/ReVanced_Extended#626]
### Application

YouTube

### Issue

In the case of live/premiere videos the playback speed should come to 1x when it catches with the live timing.

### Patch

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by sleepingiv** [comment]
Hey , I am not suggesting to disable default video speed on live videos, what I am saying is suppose I am late at a live video by 5 mins and I am playing it at 2.5x speed and after some time I catch up with live timing, then the speed should come down to 1x to avoid buffering.

**Comment by inotia00** [comment]
reflected in [revanced-patches-v2.168.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.30)

**Comment by Hennadz** [comment]
> Отражаэся в [revanced-patches-v2.168.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.30)
Tell me, please, what needs to be switched here so that the speed drop occurs not only in the background?
When the application interface is open, switching to normal speed does not occur.
Android 10
Updated Revancify
18.14.41, v2.168.42
![Screenshot_20230420-120826_MyTube](https://user-images.githubusercontent.com/130844239/233321976-663c13d9-9fdf-4132-a34f-8dcf27692beb.png)
