### ISSUE TITLE
suggestion: include "Fix video playback issues" option

### ISSUE THREAD

**Issue by chofnar** [inotia00/ReVanced_Extended#66]
### Application

YouTube

### Description

When patching with the revanced patches, there's an option in the settings to "Fix video playback issues" - as sometimes videos simply don't start and get stuck. I saw that this is a mostly isolated issue and the fix doesn't work every time, but it certainly works for me and is essential. This option is missing from the menu when patching with the Extended ones.

![Screenshot_20221228_145922_YouTube](https://user-images.githubusercontent.com/47508362/209816063-e0f69e06-01b8-4e08-b738-98e580cfcb16.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
That option is located in the following path

Settings > ReVanced settings > Extended settings > Experimental Flags > Fix video playback buffer issues

![Settings](https://user-images.githubusercontent.com/108592928/209819559-404b5fcb-cd00-406f-99a6-94d97d0eb38b.png)

Q. Why is it located in `Extended settings` instead of `Miscellaneous settings`?
A. It wasn't stable enough to add to the `Miscellaneous settings`. So I classified it as `Experimental Flags`

**Comment by chofnar** [comment]
Ohhhh, right. Sorry!
