### ISSUE TITLE
bug: skip segment button goes behind end screen cards after PiP

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#701]
### Type

Other

### Application

YouTube v18.13.38
ReVanced Patches v2.168.30

### Bug description

https://user-images.githubusercontent.com/127908708/231227108-36fff345-a318-42da-b334-66ad75910773.mp4

### Steps to reproduce

1. Play a video
2. Go PiP mode
3. Return to normal mode

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
SponsorBlock code now completely follows the official ReVanced code

Therefore, even if you report a SponsorBlock related bug here, there is nothing I can fix.

SponsorBlock-related issues that occur in RVX also occur in official ReVanced.

Since SponsorBlock is completely rebased code by ReVanced Team, you will need to report the issue to the ReVanced repo to be able to fix it.

**Comment by Kuddus73** [comment]
> RVX's SponsorBlock code now completely follows the official ReVanced's code

@inotia00 I installed ReVanced and tested there but this bug is not present on it.

**Comment by inotia00** [comment]
nah.. Try testing with the dev branch (ReVanced v18.08.37)

**Comment by inotia00** [comment]
And, I don't plan to maintain SponsorBlock related code any more.

**Comment by Kuddus73** [comment]
> nah.. Try testing with the dev branch (ReVanced v18.08.37)

I tested on v18.05.40, the one the manger says recommended.

https://user-images.githubusercontent.com/127908708/233211016-600f3d09-2f1e-492e-8e23-79a6f6231612.mp4

![Screenshot_20230419_230303](https://user-images.githubusercontent.com/127908708/233211175-f7122c55-b0d3-4aee-8be2-90a76eb7039f.jpg)

**I tried to test it also on v18.08.37 but says unsupported.**
![Screenshot_20230419_231059](https://user-images.githubusercontent.com/127908708/233211406-f052c617-14ef-4b94-80f4-b6497cf6ab61.jpg)

**Comment by inotia00** [comment]
The reason v18.05.40 is listed as recommended is because you tried patching to the main branch (stable).

In the dev branch, the recommended version is marked as v18.08.37, and includes rebase related to SponsorBlock.
https://github.com/revanced/revanced-patches/releases/tag/v2.168.0-dev.1

Unfortunately, currently there is no way to test the dev branch other than the CLI method.

**Comment by Kuddus73** [comment]
I installed v18.08.37 through CLI and still no bugs:

https://user-images.githubusercontent.com/127908708/233222439-8ec66881-4b67-43f8-91d4-2d3273f6673a.mp4

I used these:
![Screenshot (604)](https://user-images.githubusercontent.com/127908708/233222543-38fef5f2-693a-4201-8053-2c9d41e79882.png)

**Is it because I used v2.168.0-dev.5 of CLI instead of v2.168.0-dev.1?**

**Comment by inotia00** [comment]
As mentioned before, I no longer maintain SponsorBlock related functions, so I have no plans to fix them.

But today's commit added SponsorBlock hightlight related features.
It includes an additional rebase related to SponsorBlock, so please test with the new release(v2.168.42) as it comes out today.
