### ISSUE TITLE
bug: App shuts automatically when background playing while keeping screen off

### ISSUE THREAD

**Issue by Ktgt15** [inotia00/ReVanced_Extended#723]
### Type

Error at runtime

### Application

Latest version 

### Bug description

When playing any video and turning off the screen from power button, the video keeps playing for a while and then the app closes automatically. And then i have to wake the screen again, open YouTube Revanced again, and find my video. 

### Steps to reproduce

Step 1 : open app
Step 2 : play any video
Step 3 : push to power button to turn off screen
Step 4 : wait for a while and the video stops playing and app shuts itself. 

### Relevant log output

```shell
NA
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by s23ultra512** [comment]
Is Youtube app in the unrestricted mode in your phones battery settings? If you put your app in the restricted list and power off the screen then Yoitube app wont be able to run in the background.

**Comment by inotia00** [comment]
please add the YouTube version you tried to patch, and the revanced-patches version

**Comment by kevinr99089** [comment]
Check the settings of the application (of the phone),
![Screenshot_20230416_024406_Settings](https://user-images.githubusercontent.com/93716347/232260270-430fbb53-82fa-4638-8b35-19de334b05a6.png)

and in the battery tab, make sure that the "restricted" option is not checked, and if it is "optimized" that is checked, check your optimization settings (Settings>Battery and Device Care>Battery>Background usage limits)
![Screenshot_20230416_024419_Device care](https://user-images.githubusercontent.com/93716347/232260283-1087a6d6-27ce-426a-a8fd-c278387affb3.png)

This "Bug" already happened to me and it was because of this, it is the device that closes the application automatically when the phone is in standby to optimize it.

**Comment by inotia00** [comment]
If no further information is provided, I will close the issue.
Please fill in the detailed information and reopen
