### ISSUE TITLE
feat(patch): Hide paid content + blank space on group of buttons

### ISSUE THREAD

**Issue by GhislainSamy** [inotia00/ReVanced_Extended#79]
### Application

YouTube

### Issue

I had already done this on the desktop version of YouTube with css : https://userstyles.org/styles/256204/youtube-hide-paid-content-more

I would like the paid parts to no longer be displayed.
I noticed that there is a blank space when hiding the download /& thanks group of button.

### Patch

![5hmtebc1919a1](https://user-images.githubusercontent.com/45396212/210080264-77c0405b-9da7-42de-8980-3f82085ebd00.jpg)
![45z0tnf1919a1](https://user-images.githubusercontent.com/45396212/210080265-b2030ec6-6fa6-4665-879c-8ec28f7cec6a.jpg)
![672udl81919a1](https://user-images.githubusercontent.com/45396212/210080266-21f55765-f3a4-458e-aa4a-3c61061b39d6.jpg)
![pimeef41919a1](https://user-images.githubusercontent.com/45396212/210080267-4469efc9-9446-496d-a61d-91d09fe7c502.jpg)

### Motivation

Is more confortable.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
impossible
It is not dependent on the layout like xml or smali

On the server side, the layout is received in the form of a byte buffer (litho)

Some byte buffers are impossible to decode

Therefore, custom is very limited

[possible]
- remove decoded bytes buffers
(current adblock method)

-take changes some value by hooking the textview
(Return YouTube Dislike)

[impossible]
- remove bytes buffers that are impossible to decode

- add new buffer certain layout
(because full decode litho is impossible)

patch-request here is mostly impossible requests

**Comment by GhislainSamy** [comment]
Understood, thank you again for your work 😊

**Comment by inotia00** [comment]
That's impossible too
If it was possible I would have already fixed it
