### ISSUE TITLE
Suggestion: Add 3 strings "Hide subscriptions button" to Crowdin translation project

### ISSUE THREAD

**Issue by buiducanh142qn** [inotia00/ReVanced_Extended#833]
![Screenshot_2023-04-23-07-47-45-278_bin mt plus](https://user-images.githubusercontent.com/54460494/233814799-c2973d5f-1fc6-491a-af68-48290e8fbd44.jpg)
In Vietnamese, I prefer to translate "Home button", "Shorts button" as "Home tab" and "Shorts tab" respectively, because it is more accurate. Therefore, I suggest adding these three "Hide Subscriptions button" strings to Crowdin translation project so that translators can translate them correctly according to their intentions.

**Comment by inotia00** [comment]
https://github.com/inotia00/revanced-patches/blob/d30aa8890456e31d59e3806c4e2c969a42da1aaf/src/main/resources/youtube/settings/values-v21/strings.xml#L46
`revanced_hide_subscriptions_button_title` shares a string resource with `revanced_hide_shorts_player_subscriptions_button_title`

(Because they both use the same strings, only one string resource was uploaded to crowdin)

![crowdin](https://user-images.githubusercontent.com/108592928/233815273-06e6e272-867c-4285-b975-e5348bf09884.png)

Since I'm on the verge of exceeding crowdin's free plan cap, I've removed the redundant string resources from crowdin.

If my crowdin project exceeds the upper limit of the free plan, as you have experienced before, all projects will be suspended and you will no longer be able to access the crowdin project.
