### ISSUE TITLE
feat(patch): integrated update section

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#848]
### Application

YouTube

### Issue

Need integrated update option in YouTube revanced extended.

### Patch

Some alternative apps provide integrated built in updater option in their apps for easy update. So its better if this app has in built update option rather than separate app like revanced manager and going on website to update.

### Motivation

It will easy to update the app. Less time consuming and efficient storage management.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Unfortunately, ReVanced is not intended to distribute prebuilt apks from birth.

The reason why Vanced was discontinued is due to the distribution of prebuilt apk, ReVanced Team said that ReVanced provides only the core source needed for patching and passes the patching process on to users.

This is why ReVanced was able to get no sanctions from Google, and why Github was able to get no DMCA takedown.

This request could not be accepted as it could threaten the existence of the ReVanced project.
