### ISSUE TITLE
About protobuf patch

### ISSUE THREAD

**Issue by Mohammed1520** [inotia00/ReVanced_Extended#919]
### Type

Other

### Application

YouTube 18.16.39

### Bug description

In the latest releases of revanced patches . It was stated that protobuf mode is set to be On by default. But on playing videos buffering appears and to solve that you need to disable and re-enable the protobuf setting 

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Screenshots or videos

.

### Solution

When default mode is ON it should do what is intended to do .. it is simple problem and can be ignored but i want to notify you sir .. big thanks for your great efforts 🥰

### Additional context

.

### Device Environment

Android 12 EMUI 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Even though I tested it, it doesn't reproduce

1. patch & clean Installation
2. don't touch any settings
3. Log in with the account having the video buffering issue
4. since protobuf spoof is applied, there is no video buffer issue

I also checked the patches and integrations, but didn't find anything out of the ordinary.
