### ISSUE TITLE
bug: <title> 

### ISSUE THREAD

**Issue by BKM71** [inotia00/ReVanced_Extended#964]
### Type

Error while patching

### Application

V18.16.39

### Bug description

Telefonun ekran kilidi kapaliyken arka planda kisa sure video oynatıkdan sonra uygulama komple kapanıyor 

### Steps to reproduce

Sorunlu

### Relevant log output

```shell
Sorunlu
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Please meet the following form and open the issue again.

-The tools used in patch
: E.G. Revanced Manager, CLI, RVX-Builder, Revancify

-At this issue is also reproduced in Youtube without patched

-The screen shot/screen record when the issue occurs or when issues occur

-The content must be written in English
