### ISSUE TITLE
question: Regarding the future and feature of microG 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#985]
### Application

mMicroG

### Description

1) With the release of mMicroG(mM), what's the future of Vanced MicroG(VM) ? Will there be no more updates to that version of MicroG?
2) Is mM's functionalities similar to VM's or does it have more functions? 
3) Is it necessary that the feature requests to mM be done via patching the app? Can't it be implemented within the apk like how VM was? Like having the hide app icon in app launcher?
4) Custom icon or naming and themeing (amoled black/material you) is an understandable patch as it depends on the user but I believe having the hide icon in launcher being implemented within the app and providing an option to toggle it on/off is a better approach.
5) If a device is having multiple account and if you intend to add only one account to mM, there's a pop-up asking to access the other account and the only way to stop the popup from reappearing is to allow this access. Is this actually necessary? And what's it accessing if we're not logging into that account via mM?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
1. VancedMicroG is discontinued

2, 3, 4. mMicroG aims to match 100% with the official MicroG.

It can be understood as MicroG that can be used by NON-ROOT users as well.

Therefore, all functions provided by VancedMicroG are missing.
e.g.
- Hide icon in app drawer
- Support for Huawei devices

Since the goal is to replicate the official MicroG's vanilla source, there are no additional plans for new features or customizations.

5. This is an official MicroG issue https://github.com/microg/GmsCore/issues/1927
