### ISSUE TITLE
feat(patch): AV1 codec

### ISSUE THREAD

**Issue by Adity1243** [inotia00/ReVanced_Extended#995]
### Application

YouTube

### Issue

Av1 codec patch

### Patch

Can you add force AV1 codec just like force VP9 codec or add compatibility to those devices which are not supported to this codec.

### Motivation

It will good to watch in clear YouTube videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
I think we shouldn't add it because if your device can play AV1, it will automatically turn on this feature. If we turn on AV1 when your devices are not support it, it can't play video and crash

**Comment by Adity1243** [comment]
I was saying because lots of video players can play videos with unsupported video format and codecs which cannot be played by pre installed video player on android.

For example :- MX player and VLC player my device didnt support Dolby atmos videos in pre installed video player but I can play those videos in vlc and mx player if that can happens then why not in YouTube if it support AV1 codec

**Comment by Adity1243** [comment]
And it will improve the rendering of that codec to those devices which are support it by default.

**Comment by Shaarigan** [comment]
> I was saying because lots of video players can play videos with unsupported video format and codecs which cannot be played by pre installed video player on android.
> 
> For example :- MX player and VLC player my device didnt support Dolby atmos videos in pre installed video player but I can play those videos in vlc and mx player if that can happens then why not in YouTube if it support AV1 codec i mean its worth it if success.

This may end up being buggy:
`Q: AV01 does not play / Why is VP9 slow on my device?

A: Because AV01 is very new, most TVs and TV boxes not not offer hardware support and cannot play AV01 at all.

If your device has hardware support for a codec, videos using that codec should play smoothly. High resolutions might also be slow in VP9 on cheap TV boxes that don't officially support 4k. Your device probably can play VP9 videos even without hardware support, however this requires a powerful CPU to run smoothly. Fixing AV01 without hardware support is technically possible, but currently not planned and probably not efficient enough`

https://github.com/inotia00/ReVanced_Extended/issues/980#issue-1699056690

**Comment by inotia00** [comment]
In case of YouTube, I have no plans to add new features.
